"""Intel Quartus tool catalogue.

Thin Tcl wrappers over Quartus's standard Tcl packages
(``quartus::project``, ``quartus::flow``, ``quartus::sta``, etc.).
Quartus commands are project-scoped; most ``set_global_assignment`` /
``get_global_assignment`` calls cover the same surface as Vivado's
typed tool surface.
"""

from __future__ import annotations

from fpga_mcp.tool_defs import ArgSpec, ToolSpec


def _t(name, tcl, summary, category, args=None, notes="", timeout=600.0):
    return ToolSpec(
        name=name,
        tcl_template=tcl,
        summary=summary,
        category=category,
        vendor="quartus",
        args=args or [],
        notes=notes,
        timeout=timeout,
    )


SPECS: list[ToolSpec] = []

# ============================================================================
# Project & file management
# ============================================================================

SPECS += [
    _t(
        "q_project_new",
        "project_new -name {{{{name}}}} -family {{{{family}}}} -part {{{{part}}}} -overwrite",
        "Create a new Quartus project.",
        "project",
        [
            ArgSpec("name"),
            ArgSpec("family", "e.g. Cyclone V."),
            ArgSpec("part", "e.g. 5CGXFC5C6F23C7."),
        ],
    ),
    _t(
        "q_project_open",
        "project_open {{{{name}}}}",
        "Open an existing Quartus project by revision name.",
        "project",
        [ArgSpec("name")],
    ),
    _t("q_project_close", "project_close", "Close the current project.", "project"),
    _t(
        "q_project_exists",
        "project_exists {{{{name}}}}",
        "Return 1 if the project file exists.",
        "project",
        [ArgSpec("name")],
    ),
    _t(
        "q_is_project_open",
        "is_project_open",
        "Return 1 if a project is currently open.",
        "project",
    ),
    _t(
        "q_get_current_revision",
        "get_current_revision",
        "Return the current revision name.",
        "project",
    ),
    _t(
        "q_create_revision",
        "create_revision -name {{{{name}}}}",
        "Create a new revision.",
        "project",
        [ArgSpec("name")],
    ),
    _t(
        "q_delete_revision",
        "delete_revision -name {{{{name}}}}",
        "Delete a revision.",
        "project",
        [ArgSpec("name")],
    ),
    _t(
        "q_set_current_revision",
        "set_current_revision {{{{name}}}}",
        "Switch to a different revision.",
        "project",
        [ArgSpec("name")],
    ),
    _t("q_get_revisions", "get_revisions", "List all revisions in the project.", "project"),
    _t(
        "q_get_part",
        "get_global_assignment -name DEVICE",
        "Return the project's DEVICE.",
        "project",
    ),
    _t(
        "q_set_part",
        "set_global_assignment -name DEVICE {{{{part}}}}",
        "Set the DEVICE assignment.",
        "project",
        [ArgSpec("part")],
    ),
    _t(
        "q_get_family",
        "get_global_assignment -name FAMILY",
        "Return the project's FAMILY.",
        "project",
    ),
    _t(
        "q_set_family",
        "set_global_assignment -name FAMILY {{{{family}}}}",
        "Set the FAMILY assignment.",
        "project",
        [ArgSpec("family")],
    ),
    _t(
        "q_get_top_entity",
        "get_global_assignment -name TOP_LEVEL_ENTITY",
        "Return the top entity.",
        "project",
    ),
    _t(
        "q_set_top_entity",
        "set_global_assignment -name TOP_LEVEL_ENTITY {{{{top}}}}",
        "Set the top entity.",
        "project",
        [ArgSpec("top")],
    ),
    _t(
        "q_set_verilog_file",
        "set_global_assignment -name VERILOG_FILE {{{{file}}}}",
        "Add a Verilog file.",
        "fileset",
        [ArgSpec("file")],
    ),
    _t(
        "q_set_systemverilog_file",
        "set_global_assignment -name SYSTEMVERILOG_FILE {{{{file}}}}",
        "Add a SystemVerilog file.",
        "fileset",
        [ArgSpec("file")],
    ),
    _t(
        "q_set_vhdl_file",
        "set_global_assignment -name VHDL_FILE {{{{file}}}}",
        "Add a VHDL file.",
        "fileset",
        [ArgSpec("file")],
    ),
    _t(
        "q_set_sdc_file",
        "set_global_assignment -name SDC_FILE {{{{file}}}}",
        "Add an SDC constraint file.",
        "fileset",
        [ArgSpec("file")],
    ),
    _t(
        "q_set_qsf_file",
        "set_global_assignment -name QSF_FILE {{{{file}}}}",
        "Add a QSF include file.",
        "fileset",
        [ArgSpec("file")],
    ),
    _t(
        "q_set_search_path",
        "set_global_assignment -name SEARCH_PATH {{{{path}}}}",
        "Add a Verilog include search path.",
        "fileset",
        [ArgSpec("path")],
    ),
    _t(
        "q_set_verilog_version",
        "set_global_assignment -name VERILOG_VERSION {{{{version}}}}",
        "Set Verilog version (e.g. Verilog-2001).",
        "fileset",
        [ArgSpec("version")],
    ),
    _t(
        "q_set_vhdl_version",
        "set_global_assignment -name VHDL_VERSION {{{{version}}}}",
        "Set VHDL version (e.g. VHDL-2008).",
        "fileset",
        [ArgSpec("version")],
    ),
    _t(
        "q_remove_assignment",
        "remove_global_assignment -name {{{{name}}}}",
        "Remove a global assignment.",
        "fileset",
        [ArgSpec("name")],
    ),
    _t(
        "q_get_all_assignments",
        "get_all_assignments -name *",
        "Return every global assignment (verbose).",
        "fileset",
    ),
    _t(
        "q_set_instance_assignment",
        "set_instance_assignment -to {{{{to}}}} -name {{{{name}}}} {{{{value}}}}",
        "Set a per-instance assignment.",
        "fileset",
        [ArgSpec("to", "Instance path."), ArgSpec("name", "Assignment name."), ArgSpec("value")],
    ),
    _t(
        "q_get_instance_assignment",
        "get_instance_assignment -to {{{{to}}}} -name {{{{name}}}}",
        "Get a per-instance assignment.",
        "fileset",
        [ArgSpec("to"), ArgSpec("name")],
    ),
    _t(
        "q_remove_instance_assignment",
        "remove_instance_assignment -to {{{{to}}}} -name {{{{name}}}}",
        "Remove a per-instance assignment.",
        "fileset",
        [ArgSpec("to"), ArgSpec("name")],
    ),
    _t(
        "q_set_pin_location",
        "set_location_assignment PIN_{{{{pin}}}} -to {{{{port}}}}",
        "Assign a pin to a port.",
        "fileset",
        [ArgSpec("port"), ArgSpec("pin")],
    ),
    _t(
        "q_get_pin_location",
        "get_instance_assignment -to {{{{port}}}} -name LOCATION",
        "Get the pin location of a port.",
        "fileset",
        [ArgSpec("port")],
    ),
    _t(
        "q_set_io_standard",
        "set_instance_assignment -to {{{{port}}}} -name IO_STANDARD {{{{standard}}}}",
        "Set IOSTANDARD of a port.",
        "fileset",
        [ArgSpec("port"), ArgSpec("standard")],
    ),
    _t(
        "q_set_weak_pullup",
        "set_instance_assignment -to {{{{port}}}} -name WEAK_PULL_UP ON",
        "Enable weak pull-up on a port.",
        "fileset",
        [ArgSpec("port")],
    ),
    _t(
        "q_set_current_strength",
        "set_instance_assignment -to {{{{port}}}} -name CURRENT_STRENGTH_NEW {{{{ma}}}}MA",
        "Set drive current (mA).",
        "fileset",
        [ArgSpec("port"), ArgSpec("ma")],
    ),
    _t(
        "q_set_slew_rate",
        "set_instance_assignment -to {{{{port}}}} -name SLEW_RATE 1",
        "Set fast slew on a port.",
        "fileset",
        [ArgSpec("port")],
    ),
    _t(
        "q_set_global_clock",
        "set_instance_assignment -to {{{{port}}}} -name GLOBAL_SIGNAL ON",
        "Promote a signal to a global clock.",
        "fileset",
        [ArgSpec("port")],
    ),
]

# ============================================================================
# Flow / compilation
# ============================================================================

SPECS += [
    _t(
        "q_execute_map",
        "execute_module -tool map",
        "Run Analysis & Synthesis.",
        "flow",
        timeout=14400.0,
    ),
    _t(
        "q_execute_fit",
        "execute_module -tool fit",
        "Run Fitter (place & route).",
        "flow",
        timeout=14400.0,
    ),
    _t(
        "q_execute_asm",
        "execute_module -tool asm",
        "Run Assembler (bitstream generation).",
        "flow",
        timeout=3600.0,
    ),
    _t(
        "q_execute_sta",
        "execute_module -tool sta",
        "Run Static Timing Analyzer.",
        "flow",
        timeout=3600.0,
    ),
    _t(
        "q_execute_eda",
        "execute_module -tool eda",
        "Run EDA Netlist Writer.",
        "flow",
        timeout=3600.0,
    ),
    _t("q_execute_pow", "execute_module -tool pow", "Run Power Analyzer.", "flow", timeout=3600.0),
    _t(
        "q_execute_all_flows",
        "execute_flow -compile",
        "Run full compile (map+fit+asm+sta).",
        "flow",
        timeout=14400.0,
    ),
    _t(
        "q_execute_flow_to",
        "execute_flow -to {{{{stage}}}}",
        "Run compile up to a stage.",
        "flow",
        [ArgSpec("stage", "e.g. asm, sta.")],
        timeout=14400.0,
    ),
    _t(
        "q_execute_flow_from",
        "execute_flow -from {{{{stage}}}}",
        "Run compile from a stage onward.",
        "flow",
        [ArgSpec("stage")],
        timeout=14400.0,
    ),
    _t(
        "q_run_quartus_map",
        "exec quartus_map --flow {{{{revision}}}} >&@stdout",
        "Run quartus_map directly (alternative to execute_module).",
        "flow",
        [ArgSpec("revision")],
        timeout=14400.0,
    ),
    _t(
        "q_run_quartus_fit",
        "exec quartus_fit --flow {{{{revision}}}} >&@stdout",
        "Run quartus_fit directly.",
        "flow",
        [ArgSpec("revision")],
        timeout=14400.0,
    ),
    _t(
        "q_run_quartus_asm",
        "exec quartus_asm --flow {{{{revision}}}} >&@stdout",
        "Run quartus_asm directly.",
        "flow",
        [ArgSpec("revision")],
        timeout=3600.0,
    ),
    _t(
        "q_run_quartus_sta",
        "exec quartus_sta --flow {{{{revision}}}} >&@stdout",
        "Run quartus_sta directly.",
        "flow",
        [ArgSpec("revision")],
        timeout=3600.0,
    ),
    _t(
        "q_run_quartus_pgm",
        'exec quartus_pgm -m jtag -o "p;{{{{sof}}}}@1" >&@stdout',
        "Program a .sof via JTAG using quartus_pgm.",
        "flow",
        [ArgSpec("sof", "Path to .sof file.")],
        timeout=600.0,
    ),
    _t(
        "q_load_package_programmer",
        "load_package programmer",
        "Load the programmer package.",
        "flow",
    ),
    _t("q_begin_execution", "begin_execution", "Begin a programmer execution session.", "flow"),
    _t("q_end_execution", "end_execution", "End a programmer execution session.", "flow"),
    _t(
        "q_add_device_pgm",
        "add_device -chip_id 1 -file {{{{sof}}}}",
        "Add a device to the programmer.",
        "flow",
        [ArgSpec("sof")],
    ),
    _t(
        "q_program_device_pgm",
        "program_device",
        "Program the configured device.",
        "flow",
        timeout=600.0,
    ),
    _t(
        "q_set_progress",
        "set_progress {{{{percent}}}}",
        "Update progress (scripted flow only).",
        "flow",
        [ArgSpec("percent")],
    ),
    _t(
        "q_create_progress",
        "create_progress {{{{name}}}}",
        "Create a progress tracker.",
        "flow",
        [ArgSpec("name")],
    ),
]

# ============================================================================
# Timing (SDC / STA)
# ============================================================================

SPECS += [
    _t(
        "q_create_clock",
        "create_clock -name {{{{name}}}} -period {{{{period}}}} [get_ports {{{{port}}}}]",
        "Create a primary clock (SDC).",
        "constraints",
        [ArgSpec("name"), ArgSpec("period"), ArgSpec("port")],
    ),
    _t(
        "q_create_generated_clock",
        "create_generated_clock -name {{{{name}}}} -source [get_ports {{{{src}}}}] -divide_by {{{{div}}}} [get_pins {{{{dst}}}}]",
        "Create a generated clock.",
        "constraints",
        [ArgSpec("name"), ArgSpec("src"), ArgSpec("div"), ArgSpec("dst")],
    ),
    _t(
        "q_set_false_path",
        "set_false_path -from [get_clocks {{{{from}}}}] -to [get_clocks {{{{to}}}}]",
        "Set a false path between clocks.",
        "constraints",
        [ArgSpec("from"), ArgSpec("to")],
    ),
    _t(
        "q_set_max_delay",
        "set_max_delay -from [get_clocks {{{{from}}}}] -to [get_clocks {{{{to}}}}] {{{{delay}}}}",
        "Set max delay.",
        "constraints",
        [ArgSpec("from"), ArgSpec("to"), ArgSpec("delay")],
    ),
    _t(
        "q_set_min_delay",
        "set_min_delay -from [get_clocks {{{{from}}}}] -to [get_clocks {{{{to}}}}] {{{{delay}}}}",
        "Set min delay.",
        "constraints",
        [ArgSpec("from"), ArgSpec("to"), ArgSpec("delay")],
    ),
    _t(
        "q_set_multicycle_path",
        "set_multicycle_path -setup -from [get_clocks {{{{from}}}}] -to [get_clocks {{{{to}}}}] {{{{n}}}}",
        "Set a multicycle path.",
        "constraints",
        [ArgSpec("from"), ArgSpec("to"), ArgSpec("n", type_hint=int)],
    ),
    _t(
        "q_set_clock_groups",
        "set_clock_groups -asynchronous -group [get_clocks {{{{g1}}}}] -group [get_clocks {{{{g2}}}}]",
        "Set clock groups as async.",
        "constraints",
        [ArgSpec("g1"), ArgSpec("g2")],
    ),
    _t(
        "q_set_clock_latency",
        "set_clock_latency -source {{{{lat}}}} [get_clocks {{{{clock}}}}]",
        "Set clock latency.",
        "constraints",
        [ArgSpec("lat"), ArgSpec("clock")],
    ),
    _t(
        "q_set_clock_uncertainty",
        "set_clock_uncertainty -setup {{{{unc}}}} [get_clocks {{{{clock}}}}]",
        "Set clock uncertainty.",
        "constraints",
        [ArgSpec("unc"), ArgSpec("clock")],
    ),
    _t(
        "q_set_input_delay",
        "set_input_delay -clock [get_clocks {{{{clock}}}}] -max {{{{delay}}}} [get_ports {{{{port}}}}]",
        "Set input delay (max).",
        "constraints",
        [ArgSpec("clock"), ArgSpec("delay"), ArgSpec("port")],
    ),
    _t(
        "q_set_output_delay",
        "set_output_delay -clock [get_clocks {{{{clock}}}}] -max {{{{delay}}}} [get_ports {{{{port}}}}]",
        "Set output delay (max).",
        "constraints",
        [ArgSpec("clock"), ArgSpec("delay"), ArgSpec("port")],
    ),
    _t(
        "q_set_clock_groups_exclusive",
        "set_clock_groups -exclusive -group [get_clocks {{{{g1}}}}] -group [get_clocks {{{{g2}}}}]",
        "Set clock groups as exclusive.",
        "constraints",
        [ArgSpec("g1"), ArgSpec("g2")],
    ),
    _t(
        "q_set_disable_timing",
        "set_disable_timing -from [get_pins {{{{from}}}}] -to [get_pins {{{{to}}}}]",
        "Disable timing arcs between two pins.",
        "constraints",
        [ArgSpec("from"), ArgSpec("to")],
    ),
    _t("q_get_clocks", "get_clocks", "List all clocks.", "constraints"),
    _t(
        "q_get_clocks_pattern",
        "get_clocks {{{{pattern}}}}",
        "List clocks matching PATTERN.",
        "constraints",
        [ArgSpec("pattern")],
    ),
    _t("q_all_clocks", "all_clocks", "Return all clocks.", "constraints"),
    _t("q_all_inputs", "all_inputs", "Return all input ports.", "constraints"),
    _t("q_all_outputs", "all_outputs", "Return all output ports.", "constraints"),
    _t("q_all_registers", "all_registers", "Return all registers.", "constraints"),
    _t(
        "q_create_timing_netlist",
        "create_timing_netlist",
        "Build the STA timing netlist.",
        "timing_reports",
    ),
    _t("q_read_sdc", "read_sdc", "Read the project's SDC into the STA netlist.", "timing_reports"),
    _t(
        "q_update_timing_netlist",
        "update_timing_netlist",
        "Update the STA timing netlist.",
        "timing_reports",
    ),
    _t(
        "q_report_timing",
        "report_timing -npaths {{{{n}}}} -return_string",
        "Report top-N paths.",
        "timing_reports",
        [ArgSpec("n", required=False, default=10, type_hint=int)],
    ),
    _t(
        "q_report_timing_from_to",
        "report_timing -from [get_pins {{{{from}}}}] -to [get_pins {{{{to}}}}] -return_string",
        "Report timing between two pins.",
        "timing_reports",
        [ArgSpec("from"), ArgSpec("to")],
    ),
    _t(
        "q_report_timing_summary",
        "report_timing_summary -return_string",
        "Report timing summary.",
        "timing_reports",
    ),
    _t(
        "q_report_clock_transfers",
        "report_clock_transfers -return_string",
        "Report clock-to-clock transfers.",
        "timing_reports",
    ),
    _t(
        "q_report_path",
        "report_path -from [get_pins {{{{from}}}}] -to [get_pins {{{{to}}}}] -return_string",
        "Report a single path.",
        "timing_reports",
        [ArgSpec("from"), ArgSpec("to")],
    ),
    _t(
        "q_get_failing_paths",
        "get_timing_paths -npaths {{{{n}}}} -slack_lesser_than 0",
        "Get failing paths as objects.",
        "timing_reports",
        [ArgSpec("n", required=False, default=10, type_hint=int)],
    ),
    _t(
        "q_get_min_delay",
        "get_min_delay -from [get_pins {{{{from}}}}] -to [get_pins {{{{to}}}}]",
        "Get min delay between two pins.",
        "timing_reports",
        [ArgSpec("from"), ArgSpec("to")],
    ),
    _t(
        "q_get_max_delay",
        "get_max_delay -from [get_pins {{{{from}}}}] -to [get_pins {{{{to}}}}]",
        "Get max delay between two pins.",
        "timing_reports",
        [ArgSpec("from"), ArgSpec("to")],
    ),
    _t(
        "q_report_clock_relationships",
        "report_clock_relationships -return_string",
        "Report clock relationships.",
        "timing_reports",
    ),
    _t(
        "q_report_unconstrained_paths",
        "report_timing -npaths 10 -return_string -less_than -0.001",
        "Report unconstrained / failing paths only.",
        "timing_reports",
    ),
    _t(
        "q_get_setup_paths",
        "get_timing_paths -setup -npaths {{{{n}}}}",
        "Get setup paths.",
        "timing_reports",
        [ArgSpec("n")],
    ),
    _t(
        "q_get_hold_paths",
        "get_timing_paths -hold -npaths {{{{n}}}}",
        "Get hold paths.",
        "timing_reports",
        [ArgSpec("n")],
    ),
    _t(
        "q_report_recovery",
        "report_recovery -return_string",
        "Report recovery timing.",
        "timing_reports",
    ),
    _t(
        "q_report_removal",
        "report_removal -return_string",
        "Report removal timing.",
        "timing_reports",
    ),
    _t(
        "q_report_metastability",
        "report_metastability -return_string",
        "Report metastability analysis.",
        "timing_reports",
    ),
]

# ============================================================================
# Reports / utilization
# ============================================================================

SPECS += [
    _t(
        "q_report_resource",
        "report_resource -return_string",
        "Report resource utilization.",
        "utilization_reports",
    ),
    _t(
        "q_report_fmax",
        "report_fmax -return_string",
        "Report Fmax per clock.",
        "utilization_reports",
    ),
    _t("q_report_area", "report_area -return_string", "Report area.", "utilization_reports"),
    _t("q_report_io", "report_io -return_string", "Report I/O assignments.", "utilization_reports"),
    _t(
        "q_report_board",
        "report_board -return_string",
        "Report board assignments.",
        "utilization_reports",
    ),
    _t(
        "q_report_chip", "report_chip -return_string", "Report chip summary.", "utilization_reports"
    ),
    _t("q_report_drc", "report_drc -return_string", "Run DRC.", "utilization_reports"),
    _t(
        "q_report_drc_specific",
        "report_drc -check {{{{check}}}} -return_string",
        "Run a specific DRC check.",
        "utilization_reports",
        [ArgSpec("check")],
    ),
    _t(
        "q_report_logic_option",
        "report_logic_option -return_string",
        "Report logic options.",
        "utilization_reports",
    ),
    _t(
        "q_report_path_summary",
        "report_path -return_string",
        "Report paths summary.",
        "utilization_reports",
    ),
    _t("q_report_ram", "report_ram -return_string", "Report RAM usage.", "utilization_reports"),
    _t("q_report_dsp", "report_dsp -return_string", "Report DSP usage.", "utilization_reports"),
    _t(
        "q_report_assignments",
        "report_assignments -return_string",
        "Report all assignments.",
        "utilization_reports",
    ),
    _t(
        "q_report_partitions",
        "report_partitions -return_string",
        "Report partition assignments.",
        "utilization_reports",
    ),
    _t(
        "q_report_netlist",
        "report_netlist -return_string",
        "Report netlist info.",
        "utilization_reports",
    ),
    _t(
        "q_report_license",
        "report_license -return_string",
        "Report license status.",
        "utilization_reports",
    ),
    _t(
        "q_report_database_files",
        "report_database_files -return_string",
        "Report DB files.",
        "utilization_reports",
    ),
    _t(
        "q_report_setup_failures",
        "report_setup_failures -return_string",
        "Report setup failures.",
        "utilization_reports",
    ),
    _t(
        "q_report_hold_failures",
        "report_hold_failures -return_string",
        "Report hold failures.",
        "utilization_reports",
    ),
    _t(
        "q_report_recovery_failures",
        "report_recovery_failures -return_string",
        "Report recovery failures.",
        "utilization_reports",
    ),
    _t(
        "q_report_removal_failures",
        "report_removal_failures -return_string",
        "Report removal failures.",
        "utilization_reports",
    ),
    _t(
        "q_report_multicycle_failures",
        "report_multicycle_failures -return_string",
        "Report multicycle failures.",
        "utilization_reports",
    ),
    _t(
        "q_report_false_path_failures",
        "report_false_path_failures -return_string",
        "Report false path failures.",
        "utilization_reports",
    ),
    _t(
        "q_report_clock_failures",
        "report_clock_failures -return_string",
        "Report clock failures.",
        "utilization_reports",
    ),
    _t(
        "q_report_param",
        "report_parameter -name {{{{name}}}} -return_string",
        "Report a Quartus parameter.",
        "utilization_reports",
        [ArgSpec("name")],
    ),
    _t(
        "q_set_option",
        "set_global_assignment -name {{{{option}}}} {{{{value}}}}",
        "Set a Quartus option (e.g. OPTIMIZATION_TECHNIQUE).",
        "utilization_reports",
        [ArgSpec("option"), ArgSpec("value")],
    ),
    _t(
        "q_get_option",
        "get_global_assignment -name {{{{option}}}}",
        "Get a Quartus option.",
        "utilization_reports",
        [ArgSpec("option")],
    ),
    _t(
        "q_set_global_assignment_dont_touch",
        "set_instance_assignment -to {{{{to}}}} -name AUTO_CARRY_CHAINS OFF",
        "Disable auto-carry on a register.",
        "utilization_reports",
        [ArgSpec("to")],
    ),
    _t(
        "q_set_dsp_block_balanced",
        "set_global_assignment -name DSP_BLOCK_BALANCING {{{{mode}}}}",
        "Set DSP balancing mode.",
        "utilization_reports",
        [ArgSpec("mode")],
    ),
    _t(
        "q_set_router_effort",
        "set_global_assignment -name ROUTER_TIMING_OPTIMIZATION_LEVEL {{{{level}}}}",
        "Set router effort (0-10).",
        "utilization_reports",
        [ArgSpec("level")],
    ),
    _t(
        "q_set_fitter_effort",
        "set_global_assignment -name FITTER_EFFORT {{{{effort}}}}",
        "Set fitter effort (Standard, Auto Fit, Fast).",
        "utilization_reports",
        [ArgSpec("effort")],
    ),
    _t(
        "q_set_optimization_technique",
        "set_global_assignment -name OPTIMIZATION_TECHNIQUE {{{{mode}}}}",
        "Set optimization technique (Area, Speed, Balanced).",
        "utilization_reports",
        [ArgSpec("mode")],
    ),
]

# ============================================================================
# IP / Qsys
# ============================================================================

SPECS += [
    _t(
        "q_qsys_create",
        "qsys-create {{{{file}}}} --component={{{{component}}}}",
        "Create a Qsys IP file.",
        "ip",
        [ArgSpec("file"), ArgSpec("component")],
    ),
    _t(
        "q_qsys_open",
        "qsys-open {{{{file}}}}",
        "Open an existing Qsys file.",
        "ip",
        [ArgSpec("file")],
    ),
    _t("q_qsys_save", "qsys-save", "Save the current Qsys file.", "ip"),
    _t("q_qsys_close", "qsys-close", "Close the current Qsys file.", "ip"),
    _t(
        "q_qsys_add_component",
        "qsys-add-component -type {{{{type}}}} -name {{{{name}}}}",
        "Add a component to the Qsys file.",
        "ip",
        [ArgSpec("type"), ArgSpec("name")],
    ),
    _t(
        "q_qsys_remove_component",
        "qsys-remove-component -name {{{{name}}}}",
        "Remove a component.",
        "ip",
        [ArgSpec("name")],
    ),
    _t(
        "q_qsys_set_parameter",
        "qsys-set-parameter -instance {{{{inst}}}} -dict [list {{{{prop}}} {{{{value}}}}]",
        "Set a component parameter.",
        "ip",
        [ArgSpec("inst"), ArgSpec("prop"), ArgSpec("value")],
    ),
    _t(
        "q_qsys_get_parameter",
        "qsys-get-parameter -instance {{{{inst}}}} -name {{{{prop}}}}",
        "Get a component parameter.",
        "ip",
        [ArgSpec("inst"), ArgSpec("prop")],
    ),
    _t(
        "q_qsys_connect",
        "qsys-connect -from [get_pins {{{{from}}}}] -to [get_pins {{{{to}}}}]",
        "Connect two Qsys pins.",
        "ip",
        [ArgSpec("from"), ArgSpec("to")],
    ),
    _t(
        "q_qsys_disconnect",
        "qsys-disconnect -from [get_pins {{{{from}}}}] -to [get_pins {{{{to}}}}]",
        "Disconnect two Qsys pins.",
        "ip",
        [ArgSpec("from"), ArgSpec("to")],
    ),
    _t(
        "q_qsys_generate",
        "qsys-generate {{{{file}}}} --synthesis=VERILOG",
        "Generate Qsys output products.",
        "ip",
        [ArgSpec("file")],
        timeout=1800.0,
    ),
    _t("q_qsys_list_components", "qsys-list-components", "List all Qsys components.", "ip"),
    _t("q_qsys_list_connections", "qsys-list-connections", "List all Qsys connections.", "ip"),
    _t("q_qsys_validate", "qsys-validate", "Validate the current Qsys file.", "ip"),
    _t(
        "q_qsys_create_clock",
        "qsys-set-clock-source -name {{{{name}}}} -frequency {{{{freq}}}}",
        "Set Qsys clock source.",
        "ip",
        [ArgSpec("name"), ArgSpec("freq")],
    ),
    _t(
        "q_qsys_create_reset",
        "qsys-set-reset-source -name {{{{name}}}}",
        "Set Qsys reset source.",
        "ip",
        [ArgSpec("name")],
    ),
    _t(
        "q_qsys_export",
        "qsys-export -file {{{{file}}}}",
        "Export a Qsys file to another format.",
        "ip",
        [ArgSpec("file")],
    ),
    _t(
        "q_qsys_load_library",
        "qsys-load-library -name {{{{lib}}}}",
        "Load an additional Qsys library.",
        "ip",
        [ArgSpec("lib")],
    ),
    _t(
        "q_qsys_remove_library",
        "qsys-remove-library -name {{{{lib}}}}",
        "Remove a Qsys library.",
        "ip",
        [ArgSpec("lib")],
    ),
]

# ============================================================================
# Power / EDA / Misc
# ============================================================================

SPECS += [
    _t("q_report_power", "report_power -return_string", "Report power.", "utilization_reports"),
    _t(
        "q_set_power_analysis_mode",
        "set_global_assignment -name POWER_PRESET_COOLING_SOLUTION {{{{mode}}}}",
        "Set cooling solution preset.",
        "utilization_reports",
        [ArgSpec("mode")],
    ),
    _t(
        "q_set_op_cond",
        "set_global_assignment -name POWER_BOARD_THERMAL_MODEL {{{{model}}}}",
        "Set thermal model.",
        "utilization_reports",
        [ArgSpec("model")],
    ),
    _t(
        "q_set_default_switching_activity",
        "set_global_assignment -name POWER_DEFAULT_INPUT_TOGGLE_RATE {{{{rate}}}}",
        "Set default input toggle rate.",
        "utilization_reports",
        [ArgSpec("rate")],
    ),
    _t(
        "q_set_vccint",
        "set_global_assignment -name POWER_VCCINT {{{{v}}}}",
        "Set VCCINT voltage.",
        "utilization_reports",
        [ArgSpec("v")],
    ),
    _t(
        "q_set_temp_grade",
        "set_global_assignment -name DEVICE_TEMP_GRADE {{{{grade}}}}",
        "Set device temperature grade.",
        "utilization_reports",
        [ArgSpec("grade")],
    ),
    _t(
        "q_set_speed_grade",
        "set_global_assignment -name DEVICE_SPEED_GRADE {{{{grade}}}}",
        "Set device speed grade.",
        "utilization_reports",
        [ArgSpec("grade")],
    ),
    _t(
        "q_report_database",
        "report_database -return_string",
        "Report database files.",
        "utilization_reports",
    ),
    _t(
        "q_set_sim_tool",
        "set_global_assignment -name EDA_SIMULATION_TOOL {{{{tool}}}}",
        "Set simulation tool (ModelSim/Questa).",
        "utilization_reports",
        [ArgSpec("tool")],
    ),
    _t(
        "q_set_testbench_name",
        "set_global_assignment -name EDA_TEST_BENCH_NAME {{{{name}}}}",
        "Set testbench name.",
        "utilization_reports",
        [ArgSpec("name")],
    ),
    _t(
        "q_set_testbench_file",
        "set_global_assignment -name EDA_TEST_BENCH_RESOURCE_FILE {{{{file}}}}",
        "Set testbench resource file.",
        "utilization_reports",
        [ArgSpec("file")],
    ),
    _t(
        "q_set_testbench_top",
        "set_global_assignment -name EDA_TEST_BENCH_MODULE {{{{top}}}}",
        "Set testbench top module.",
        "utilization_reports",
        [ArgSpec("top")],
    ),
    _t(
        "q_set_sim_output_dir",
        "set_global_assignment -name EDA_OUTPUT_DATA_DIR {{{{dir}}}}",
        "Set EDA output directory.",
        "utilization_reports",
        [ArgSpec("dir")],
    ),
    _t(
        "q_set_sim_tool_args",
        "set_global_assignment -name EDA_TOOL_COMMAND {{{{cmd}}}}",
        "Set custom EDA tool command.",
        "utilization_reports",
        [ArgSpec("cmd")],
    ),
    _t(
        "q_set_board_part",
        "set_global_assignment -name BOARD {{{{board}}}}",
        "Set board file.",
        "utilization_reports",
        [ArgSpec("board")],
    ),
    _t(
        "q_get_board", "get_global_assignment -name BOARD", "Get board file.", "utilization_reports"
    ),
    _t(
        "q_set_revision_part",
        "set_global_assignment -name DEVICE_FAMILY {{{{family}}}}",
        "Set device family for revision.",
        "utilization_reports",
        [ArgSpec("family")],
    ),
    _t(
        "q_set_timing_driven",
        "set_global_assignment -name ROUTER_TIMING_OPTIMIZATION_LEVEL 10",
        "Enable max-effort timing-driven routing.",
        "utilization_reports",
    ),
    _t(
        "q_set_smart_compile",
        "set_global_assignment -name SMART_RECOMPILE ON",
        "Enable smart recompile.",
        "utilization_reports",
    ),
    _t(
        "q_set_incremental_compile",
        "set_global_assignment -name INCREMENTAL_COMPILATION FULL",
        "Enable incremental compilation.",
        "utilization_reports",
    ),
    _t(
        "q_set_signal_probe",
        "set_global_assignment -name SIGNALPROBE_ENABLE ON",
        "Enable SignalProbe.",
        "utilization_reports",
    ),
    _t(
        "q_run_quartus_cdb",
        "exec quartus_cdb -t {{{{script}}}} >&@stdout",
        "Run a custom Tcl script via quartus_cdb.",
        "utilization_reports",
        [ArgSpec("script")],
    ),
]
