"""Vivado tool catalogue.

These tools are thin wrappers around Vivado's native Tcl commands. They are
designed so an LLM can discover them by name and call them with keyword
arguments; the wrapper forwards to ``backend.exec_tcl``.

Catalogue is split by Vivado command family:

  - project / filesets      (~30)
  - synthesis / impl runs   (~30)
  - IP / block design       (~40)
  - constraints             (~30)
  - timing reports          (~30)
  - utilization / DRC       (~25)
  - simulation              (~20)
  - hardware manager        (~25)
  - debug cores (ILA/VIO)   (~15)
  - netlist queries         (~25)
  - part / device queries   (~15)
"""

from __future__ import annotations

from fpga_mcp.tool_defs import ArgSpec, ToolSpec


# Helper: avoid repeating the boilerplate. Most tools are pure Tcl wrappers.
def _t(
    name: str,
    tcl: str,
    summary: str,
    category: str,
    args=None,
    notes: str = "",
    timeout: float = 600.0,
) -> ToolSpec:
    return ToolSpec(
        name=name,
        tcl_template=tcl,
        summary=summary,
        category=category,
        vendor="vivado",
        args=args or [],
        notes=notes,
        timeout=timeout,
    )


SPECS: list[ToolSpec] = []

# ============================================================================
# Project & fileset management
# ============================================================================

SPECS += [
    _t(
        "viv_create_project",
        "create_project -force -part {{{{part}}}} {{{{name}}}} {{{{directory}}}}",
        "Create a Vivado project.",
        "project",
        [ArgSpec("name"), ArgSpec("directory"), ArgSpec("part", "e.g. xc7a35tcpg236-1.")],
    ),
    _t(
        "viv_create_project_in_memory",
        "create_project -in_memory -part {{{{part}}}}",
        "Create an in-memory project (no .xpr written).",
        "project",
        [ArgSpec("part")],
    ),
    _t(
        "viv_open_project",
        "open_project {{{{path}}}}",
        "Open an existing .xpr project.",
        "project",
        [ArgSpec("path", "Path to the .xpr file.")],
    ),
    _t("viv_close_project", "close_project", "Close the current project.", "project"),
    _t(
        "viv_save_project",
        "save_project -as {{{{path}}}}",
        "Save the project (optionally as a new path).",
        "project",
        [ArgSpec("path", "Optional new path.", required=False, default="")],
    ),
    _t(
        "viv_archive_project",
        "archive_project -force {{{{archive}}}} -include_config_files",
        "Archive the project to a .xpr.zip file.",
        "project",
        [ArgSpec("archive", "Output archive path.")],
    ),
    _t(
        "viv_import_project",
        "import_project {{{{path}}}} -part {{{{part}}}}",
        "Import a project from an archive or .xpr.",
        "project",
        [ArgSpec("path"), ArgSpec("part")],
    ),
    _t(
        "viv_export_project_user_template",
        "export_project_user_template -force -output {{{{path}}}}",
        "Export the project as a user template.",
        "project",
        [ArgSpec("path")],
    ),
    _t(
        "viv_current_project",
        "current_project",
        "Return the current project object name.",
        "project",
    ),
    _t("viv_get_projects", "get_projects", "List all open projects.", "project"),
    _t(
        "viv_get_project_property",
        "get_property {{{{prop}}}} [current_project]",
        "Get a top-level project property.",
        "project",
        [ArgSpec("prop", "e.g. PART, DIRECTORY, VERSION.")],
    ),
    _t(
        "viv_set_project_property",
        "set_property {{{{prop}}}} {{{{value}}}} [current_project]",
        "Set a top-level project property.",
        "project",
        [ArgSpec("prop"), ArgSpec("value")],
    ),
    _t(
        "viv_get_project_dir",
        "get_property DIRECTORY [current_project]",
        "Return the project directory.",
        "project",
    ),
    _t(
        "viv_get_part",
        "get_property PART [current_project]",
        "Return the project's target part.",
        "project",
    ),
    _t(
        "viv_set_part",
        "set_property part {{{{part}}}} [current_project]",
        "Change the target part.",
        "project",
        [ArgSpec("part")],
    ),
    _t(
        "viv_get_target_language",
        "get_property target_language [current_project]",
        "Get the default HDL (Verilog/VHDL).",
        "project",
    ),
    _t(
        "viv_set_target_language",
        "set_property target_language {{{{lang}}}} [current_project]",
        "Set the default HDL.",
        "project",
        [ArgSpec("lang", "Verilog or VHDL.")],
    ),
    _t(
        "viv_get_default_lib",
        "get_property default_lib [current_project]",
        "Get the default library name.",
        "project",
    ),
    _t(
        "viv_set_default_lib",
        "set_property default_lib {{{{lib}}}} [current_project]",
        "Set the default library name.",
        "project",
        [ArgSpec("lib")],
    ),
    # filesets
    _t(
        "viv_create_fileset",
        "create_fileset {{{{name}}}}",
        "Create a new fileset.",
        "fileset",
        [ArgSpec("name")],
    ),
    _t(
        "viv_delete_fileset",
        "delete_fileset {{{{name}}}}",
        "Delete a fileset.",
        "fileset",
        [ArgSpec("name")],
    ),
    _t("viv_current_fileset", "current_fileset", "Return the current fileset handle.", "fileset"),
    _t("viv_get_filesets", "get_filesets", "List all filesets.", "fileset"),
    _t(
        "viv_add_files",
        "add_files -norecurse {{{{files}}}}",
        "Add files to the current fileset.",
        "fileset",
        [ArgSpec("files", "List of paths.")],
    ),
    _t(
        "viv_add_files_recursive",
        "add_files -recurse {{{{dir}}}}",
        "Add all files under a directory.",
        "fileset",
        [ArgSpec("dir")],
    ),
    _t(
        "viv_import_files",
        "import_files -norecurse {{{{files}}}}",
        "Import (copy) files into the project.",
        "fileset",
        [ArgSpec("files")],
    ),
    _t(
        "viv_remove_files",
        "remove_files {{{{files}}}}",
        "Remove files from the current fileset.",
        "fileset",
        [ArgSpec("files")],
    ),
    _t("viv_get_files", "get_files", "List all source files in the project.", "fileset"),
    _t(
        "viv_get_files_of_type",
        "get_files -of_objects [get_filesets {{{{fileset}}}}] {{{{pattern}}}}",
        "List files matching a pattern in a fileset.",
        "fileset",
        [ArgSpec("fileset"), ArgSpec("pattern")],
    ),
    _t(
        "viv_set_file_property",
        "set_property {{{{prop}}}} {{{{value}}}} [get_files {{{{file}}}}]",
        "Set a property on a source file.",
        "fileset",
        [ArgSpec("file"), ArgSpec("prop"), ArgSpec("value")],
    ),
    _t(
        "viv_get_file_property",
        "get_property {{{{prop}}}} [get_files {{{{file}}}}]",
        "Get a property of a source file.",
        "fileset",
        [ArgSpec("file"), ArgSpec("prop")],
    ),
    _t(
        "viv_set_top_module",
        "set_property top {{{{top}}}} [current_fileset]",
        "Set the top-level module of the current fileset.",
        "fileset",
        [ArgSpec("top")],
    ),
    _t(
        "viv_update_compile_order",
        "update_compile_order -fileset [current_fileset]",
        "Recompute compile order for the current fileset.",
        "fileset",
    ),
    _t(
        "viv_add_constraints",
        "add_files -fileset [get_filesets constrs_1] {{{{files}}}}",
        "Add constraint files to constrs_1.",
        "fileset",
        [ArgSpec("files")],
    ),
    _t(
        "viv_set_constraint_used_in",
        "set_property used_in_synthesis true [get_files {{{{file}}}}]",
        "Mark a constraint file as used in synthesis.",
        "fileset",
        [ArgSpec("file")],
    ),
    _t(
        "viv_set_constraint_global",
        "set_property is_enabled true [get_files {{{{file}}}}]",
        "Enable a constraint file globally.",
        "fileset",
        [ArgSpec("file")],
    ),
    _t(
        "viv_make_library",
        "make_library {{{{lib}}}}",
        "Create a new user library.",
        "fileset",
        [ArgSpec("lib")],
    ),
]

# ============================================================================
# Synthesis & implementation runs
# ============================================================================

SPECS += [
    _t(
        "viv_launch_synth",
        "launch_runs synth_1 -jobs {{{{jobs}}}}",
        "Launch synth_1 with N parallel jobs.",
        "synth",
        [ArgSpec("jobs", "Parallel job count.", required=False, default=8, type_hint=int)],
        timeout=7200.0,
    ),
    _t(
        "viv_wait_on_synth",
        "wait_on_run synth_1",
        "Block until synth_1 completes.",
        "synth",
        timeout=7200.0,
    ),
    _t("viv_reset_synth_run", "reset_run synth_1", "Reset the synth_1 run.", "synth"),
    _t(
        "viv_get_synth_status",
        "get_property STATUS [get_runs synth_1]",
        "Get synth_1 status string.",
        "synth",
    ),
    _t(
        "viv_get_synth_progress",
        "get_property PROGRESS [get_runs synth_1]",
        "Get synth_1 progress %.",
        "synth",
    ),
    _t(
        "viv_set_synth_strategy",
        "set_property strategy {{{{strategy}}}} [get_runs synth_1]",
        "Set synth_1 strategy (e.g. Vivado Synthesis Defaults).",
        "synth",
        [ArgSpec("strategy")],
    ),
    _t(
        "viv_set_synth_step",
        "set_property STEPS.SYNTH_DESIGN.ARGS.DIRECTIVE {{{{directive}}}} [get_runs synth_1]",
        "Set synth_design directive.",
        "synth",
        [ArgSpec("directive")],
    ),
    _t(
        "viv_launch_impl",
        "launch_runs impl_1 -jobs {{{{jobs}}}}",
        "Launch impl_1.",
        "impl",
        [ArgSpec("jobs", required=False, default=8, type_hint=int)],
        timeout=14400.0,
    ),
    _t(
        "viv_launch_impl_to_step",
        "launch_runs impl_1 -to_step {{{{step}}}} -jobs 8",
        "Launch impl_1 stopping at STEP.",
        "impl",
        [ArgSpec("step", "e.g. write_bitstream.")],
        timeout=14400.0,
    ),
    _t(
        "viv_launch_impl_from_step",
        "launch_runs impl_1 -from_step {{{{step}}}} -jobs 8",
        "Launch impl_1 from STEP onward.",
        "impl",
        [ArgSpec("step")],
        timeout=14400.0,
    ),
    _t(
        "viv_wait_on_impl",
        "wait_on_run impl_1",
        "Block until impl_1 completes.",
        "impl",
        timeout=14400.0,
    ),
    _t("viv_reset_impl_run", "reset_run impl_1", "Reset the impl_1 run.", "impl"),
    _t(
        "viv_get_impl_status",
        "get_property STATUS [get_runs impl_1]",
        "Get impl_1 status string.",
        "impl",
    ),
    _t(
        "viv_get_impl_progress",
        "get_property PROGRESS [get_runs impl_1]",
        "Get impl_1 progress %.",
        "impl",
    ),
    _t(
        "viv_set_impl_strategy",
        "set_property strategy {{{{strategy}}}} [get_runs impl_1]",
        "Set impl_1 strategy.",
        "impl",
        [ArgSpec("strategy")],
    ),
    _t(
        "viv_set_impl_step_directive",
        "set_property STEPS.{{{{step}}}}.AR.DIRECTIVE {{{{directive}}}} [get_runs impl_1]",
        "Set a directive on a specific impl step.",
        "impl",
        [ArgSpec("step", "e.g. PLACE_DESIGN."), ArgSpec("directive", "e.g. Explore.")],
    ),
    _t("viv_get_runs", "get_runs", "List all runs.", "impl"),
    _t(
        "viv_get_run_property",
        "get_property {{{{prop}}}} [get_runs {{{{run}}}}]",
        "Get a run property.",
        "impl",
        [ArgSpec("run"), ArgSpec("prop")],
    ),
    _t(
        "viv_set_run_property",
        "set_property {{{{prop}}}} {{{{value}}}} [get_runs {{{{run}}}}]",
        "Set a run property.",
        "impl",
        [ArgSpec("run"), ArgSpec("prop"), ArgSpec("value")],
    ),
    _t(
        "viv_create_run",
        "create_run {{{{name}}}} -flow {{{{flow}}}} -strategy {{{{strategy}}}} -constrset {{{{cs}}}}",
        "Create a new impl run.",
        "impl",
        [
            ArgSpec("name"),
            ArgSpec("flow", required=False, default="Vivado Implementation"),
            ArgSpec("strategy", required=False, default="Vivado Implementation Defaults"),
            ArgSpec("cs", required=False, default="constrs_1"),
        ],
    ),
    _t("viv_delete_run", "delete_run {{{{name}}}}", "Delete a run.", "impl", [ArgSpec("name")]),
    # in-memory / open designs
    _t(
        "viv_open_run",
        "open_run {{{{run}}}}",
        "Open a synthesized/implemented run as a design.",
        "impl",
        [ArgSpec("run", "synth_1 or impl_1.")],
    ),
    _t("viv_close_design", "close_design", "Close the currently-open design.", "impl"),
    _t("viv_current_design", "current_design", "Return the current design handle.", "impl"),
    _t("viv_link_design", "link_design", "Link the design's sources.", "impl"),
    _t(
        "viv_synth_design",
        "synth_design -top {{{{top}}}} -part {{{{part}}}}",
        "Run synth_design directly on an in-memory design.",
        "synth",
        [ArgSpec("top"), ArgSpec("part", required=False, default="")],
        timeout=7200.0,
    ),
    _t(
        "viv_place_design",
        "place_design",
        "Run place_design on the open design.",
        "impl",
        timeout=14400.0,
    ),
    _t(
        "viv_route_design",
        "route_design",
        "Run route_design on the open design.",
        "impl",
        timeout=14400.0,
    ),
    _t(
        "viv_phys_opt_design",
        "phys_opt_design",
        "Run phys_opt (post-route optimization).",
        "impl",
        timeout=14400.0,
    ),
    _t("viv_opt_design", "opt_design", "Run opt_design on the open design.", "synth"),
    _t(
        "viv_write_bitstream",
        "write_bitstream -force {{{{path}}}}",
        "Write the bitstream to a file.",
        "impl",
        [ArgSpec("path")],
        timeout=3600.0,
    ),
    _t(
        "viv_write_bitstream_with_ltx",
        "write_bitstream -force -raw_bitfile -cell_placement {{{{cell}}}} {{{{path}}}}",
        "Write bitstream + probe file for a partial reconfiguration cell.",
        "impl",
        [ArgSpec("cell"), ArgSpec("path")],
        timeout=3600.0,
    ),
    _t(
        "viv_write_checkpoint",
        "write_checkpoint -force {{{{path}}}}",
        "Save the design checkpoint (.dcp).",
        "impl",
        [ArgSpec("path")],
    ),
    _t(
        "viv_open_checkpoint",
        "open_checkpoint {{{{path}}}}",
        "Open a .dcp file.",
        "impl",
        [ArgSpec("path")],
    ),
    _t(
        "viv_write_verilog_netlist",
        "write_verilog -force -mode synth_stub {{{{path}}}}",
        "Write a Verilog stub netlist.",
        "impl",
        [ArgSpec("path")],
    ),
    _t(
        "viv_write_edif",
        "write_edif -force {{{{path}}}}",
        "Write an EDIF netlist.",
        "impl",
        [ArgSpec("path")],
    ),
]

# ============================================================================
# IP / Block Design
# ============================================================================

SPECS += [
    _t(
        "viv_create_ip",
        "create_ip -name {{{{name}}}} -module_name {{{{module}}}}",
        "Create an IP instance by name.",
        "ip",
        [
            ArgSpec("name", "e.g. clk_wiz, fifo_generator."),
            ArgSpec("module", "Module/instance name."),
        ],
    ),
    _t(
        "viv_create_ip_versioned",
        "create_ip -name {{{{name}}}} -version {{{{version}}}} -module_name {{{{module}}}}",
        "Create an IP instance pinned to a version.",
        "ip",
        [ArgSpec("name"), ArgSpec("version"), ArgSpec("module")],
    ),
    _t("viv_get_ips", "get_ips", "List all IP instances.", "ip"),
    _t(
        "viv_get_ip_cell",
        "get_ips {{{{name}}}}",
        "Get an IP cell by name.",
        "ip",
        [ArgSpec("name")],
    ),
    _t(
        "viv_set_ip_property",
        "set_property -dict [list {{{{prop}}} {{{{value}}}}] [get_ips {{{{name}}}}]",
        "Set a single CONFIG.* property on an IP.",
        "ip",
        [ArgSpec("name"), ArgSpec("prop"), ArgSpec("value")],
    ),
    _t(
        "viv_set_ip_properties",
        "set_property -dict [list {{{{props}}}}] [get_ips {{{{name}}}}]",
        "Set multiple CONFIG.* properties (props is a Tcl list of key-value pairs).",
        "ip",
        [ArgSpec("name"), ArgSpec("props")],
    ),
    _t(
        "viv_get_ip_property",
        "get_property {{{{prop}}}} [get_ips {{{{name}}}}]",
        "Get a CONFIG.* property on an IP.",
        "ip",
        [ArgSpec("name"), ArgSpec("prop")],
    ),
    _t(
        "viv_generate_ip_target",
        "generate_target all [get_ips {{{{name}}}}]",
        "Generate output products for an IP.",
        "ip",
        [ArgSpec("name")],
        timeout=1800.0,
    ),
    _t(
        "viv_synth_ip",
        "synth_ip [get_ips {{{{name}}}}]",
        "Synthesize an IP instance.",
        "ip",
        [ArgSpec("name")],
        timeout=1800.0,
    ),
    _t(
        "viv_upgrade_ip",
        "upgrade_ip [get_ips {{{{name}}}}]",
        "Upgrade an out-of-date IP.",
        "ip",
        [ArgSpec("name")],
        timeout=1800.0,
    ),
    _t(
        "viv_report_ip",
        "report_property [get_ips {{{{name}}}}]",
        "Report all properties of an IP.",
        "ip",
        [ArgSpec("name")],
    ),
    _t(
        "viv_get_ip_supported_props",
        "list_property_value -class ip [get_ips {{{{name}}}}]",
        "List supported CONFIG.* properties.",
        "ip",
        [ArgSpec("name")],
    ),
    _t(
        "viv_get_ipdefs",
        "get_ipdefs -name {{{{pattern}}}}",
        "List IP definitions matching PATTERN.",
        "ip",
        [ArgSpec("pattern", "e.g. clk_wiz*.")],
    ),
    _t("viv_list_ip_catalog", "ipx::list_core [get_ipdefs]", "List the entire IP catalog.", "ip"),
    _t(
        "viv_create_ip_repo",
        "set_property ip_repo_paths [list {{{{path}}}}] [current_project]",
        "Register a custom IP repo path.",
        "ip",
        [ArgSpec("path")],
    ),
    _t("viv_update_ip_catalog", "update_ip_catalog", "Refresh the IP catalog.", "ip"),
    _t(
        "viv_create_ip_run",
        "create_ip_run [get_ips {{{{name}}}}]",
        "Create an OOC IP run.",
        "ip",
        [ArgSpec("name")],
    ),
    _t(
        "viv_delete_ip_run",
        "delete_ip_run [get_ips {{{{name}}}}]",
        "Delete an OOC IP run.",
        "ip",
        [ArgSpec("name")],
    ),
    _t(
        "viv_reset_ip_run",
        "reset_run [get_property IP_CORE [get_ips {{{{name}}}}]]",
        "Reset an IP's OOC run.",
        "ip",
        [ArgSpec("name")],
    ),
    _t(
        "viv_lock_ip",
        "set_property IS_LOCKED true [get_ips {{{{name}}}}]",
        "Lock an IP against edits.",
        "ip",
        [ArgSpec("name")],
    ),
    _t(
        "viv_unlock_ip",
        "set_property IS_LOCKED false [get_ips {{{{name}}}}]",
        "Unlock an IP.",
        "ip",
        [ArgSpec("name")],
    ),
    # Block Design
    _t(
        "viv_create_bd",
        "create_bd_design {{{{name}}}}",
        "Create a block design.",
        "block_design",
        [ArgSpec("name")],
    ),
    _t(
        "viv_open_bd",
        "open_bd_design {{{{path}}}}",
        "Open a block design.",
        "block_design",
        [ArgSpec("path")],
    ),
    _t(
        "viv_close_bd",
        "close_bd_design [current_bd_design]",
        "Close the current block design.",
        "block_design",
    ),
    _t("viv_current_bd", "current_bd_design", "Return the current BD handle.", "block_design"),
    _t("viv_save_bd", "save_bd_design", "Save the current block design.", "block_design"),
    _t(
        "viv_validate_bd",
        "validate_bd_design",
        "Validate the BD (run consistency checks).",
        "block_design",
    ),
    _t(
        "viv_make_wrapper",
        "make_wrapper -files [get_files {{{{bd}}}}.srcs/sources_1/bd/{{{{bd}}}}/{{{{bd}}}}.bd] -top",
        "Generate the BD HDL wrapper as the new top.",
        "block_design",
        [ArgSpec("bd", "BD name.")],
    ),
    _t(
        "viv_add_bd_cell",
        "create_bd_cell -type ip -vlnv {{{{vlnv}}}} {{{{name}}}}",
        "Add an IP cell to the BD.",
        "block_design",
        [ArgSpec("vlnv"), ArgSpec("name")],
    ),
    _t(
        "viv_add_bd_cell_block",
        "create_bd_cell -type block {{{{name}}}}",
        "Add a block (sub-BD) cell.",
        "block_design",
        [ArgSpec("name")],
    ),
    _t(
        "viv_delete_bd_cell",
        "delete_bd_objs [get_bd_cells {{{{name}}}}]",
        "Delete a BD cell.",
        "block_design",
        [ArgSpec("name")],
    ),
    _t("viv_get_bd_cells", "get_bd_cells", "List all BD cells.", "block_design"),
    _t(
        "viv_get_bd_cell_property",
        "get_property {{{{prop}}}} [get_bd_cells {{{{name}}}}]",
        "Get a property on a BD cell.",
        "block_design",
        [ArgSpec("name"), ArgSpec("prop")],
    ),
    _t(
        "viv_set_bd_cell_property",
        "set_property {{{{prop}}}} {{{{value}}}} [get_bd_cells {{{{name}}}}]",
        "Set a property on a BD cell.",
        "block_design",
        [ArgSpec("name"), ArgSpec("prop"), ArgSpec("value")],
    ),
    _t(
        "viv_set_bd_cell_config",
        "set_property -dict [list {{{{prop}}} {{{{value}}}}] [get_bd_cells {{{{name}}}}]",
        "Set a CONFIG.* on a BD cell.",
        "block_design",
        [ArgSpec("name"), ArgSpec("prop"), ArgSpec("value")],
    ),
    _t(
        "viv_connect_bd_net",
        "connect_bd_net [get_bd_pins {{{{src}}}}] [get_bd_pins {{{{dst}}}}]",
        "Connect two BD nets.",
        "block_design",
        [ArgSpec("src"), ArgSpec("dst")],
    ),
    _t(
        "viv_connect_bd_intf_net",
        "connect_bd_intf_net [get_bd_intf_pins {{{{src}}}}] [get_bd_intf_pins {{{{dst}}}}]",
        "Connect two BD interface nets.",
        "block_design",
        [ArgSpec("src"), ArgSpec("dst")],
    ),
    _t(
        "viv_create_bd_port",
        "create_bd_port -dir {{{{dir}}}} {{{{name}}}}",
        "Create a BD external port.",
        "block_design",
        [ArgSpec("dir", "I, O, or IO."), ArgSpec("name")],
    ),
    _t(
        "viv_create_bd_intf_port",
        "create_bd_intf_port -mode {{{{mode}}}} -vlnv {{{{vlnv}}}} {{{{name}}}}",
        "Create a BD external interface port.",
        "block_design",
        [ArgSpec("mode", "Master/Slave/Monitor."), ArgSpec("vlnv"), ArgSpec("name")],
    ),
    _t("viv_get_bd_ports", "get_bd_ports", "List BD external ports.", "block_design"),
    _t("viv_get_bd_pins", "get_bd_pins", "List all BD pins.", "block_design"),
    _t("viv_get_bd_intf_pins", "get_bd_intf_pins", "List all BD interface pins.", "block_design"),
    _t("viv_get_bd_nets", "get_bd_nets", "List all BD nets.", "block_design"),
    _t(
        "viv_apply_bd_automation",
        "apply_bd_automation -rule {{{{rule}}}}",
        "Run BD automation rule.",
        "block_design",
        [ArgSpec("rule")],
    ),
    _t(
        "viv_set_bd_automation_target",
        "set_property automation_target {{{{target}}}} [current_bd_design]",
        "Set BD automation target.",
        "block_design",
        [ArgSpec("target")],
    ),
]

# ============================================================================
# Constraints
# ============================================================================

SPECS += [
    _t(
        "viv_create_clock",
        "create_clock -name {{{{name}}}} -period {{{{period}}}} -waveform {{0 {{{{ duty }}}}}} [get_ports {{{{port}}}}]",
        "Define a primary clock.",
        "constraints",
        [
            ArgSpec("name"),
            ArgSpec("period", "Period in ns."),
            ArgSpec("duty", "High time in ns.", required=False, default="5"),
            ArgSpec("port"),
        ],
    ),
    _t(
        "viv_create_generated_clock",
        "create_generated_clock -name {{{{name}}}} -source [get_pins {{{{src}}}}] -divide_by {{{{div}}}} [get_pins {{{{dst}}}}]",
        "Define a generated (derived) clock.",
        "constraints",
        [ArgSpec("name"), ArgSpec("src"), ArgSpec("div"), ArgSpec("dst")],
    ),
    _t(
        "viv_set_false_path",
        "set_false_path -from [get_clocks {{{{from}}}}] -to [get_clocks {{{{to}}}}]",
        "Mark a clock crossing as a false path.",
        "constraints",
        [ArgSpec("from"), ArgSpec("to")],
    ),
    _t(
        "viv_set_false_path_through",
        "set_false_path -through [get_pins {{{{through}}}}]",
        "Set a false path through a pin.",
        "constraints",
        [ArgSpec("through")],
    ),
    _t(
        "viv_set_max_delay",
        "set_max_delay -datapath_only -from [get_clocks {{{{from}}}}] -to [get_clocks {{{{to}}}}] {{{{delay}}}}",
        "Set max delay for a CDC path.",
        "constraints",
        [ArgSpec("from"), ArgSpec("to"), ArgSpec("delay")],
    ),
    _t(
        "viv_set_min_delay",
        "set_min_delay -from [get_pins {{{{from}}}}] -to [get_pins {{{{to}}}}] {{{{delay}}}}",
        "Set min delay.",
        "constraints",
        [ArgSpec("from"), ArgSpec("to"), ArgSpec("delay")],
    ),
    _t(
        "viv_set_multicycle_path",
        "set_multicycle_path -setup -from [get_clocks {{{{from}}}}] -to [get_clocks {{{{to}}}}] {{{{n}}}}",
        "Set a multicycle path (setup).",
        "constraints",
        [ArgSpec("from"), ArgSpec("to"), ArgSpec("n", "Cycles.", type_hint=int)],
    ),
    _t(
        "viv_set_clock_groups",
        "set_clock_groups -asynchronous -group [get_clocks {{{{g1}}}}] -group [get_clocks {{{{g2}}}}]",
        "Declare two clock groups as asynchronous.",
        "constraints",
        [ArgSpec("g1"), ArgSpec("g2")],
    ),
    _t(
        "viv_set_clock_groups_phys_exclusive",
        "set_clock_groups -physically_exclusive -group [get_clocks {{{{g1}}}}] -group [get_clocks {{{{g2}}}}]",
        "Declare two clock groups physically exclusive.",
        "constraints",
        [ArgSpec("g1"), ArgSpec("g2")],
    ),
    _t(
        "viv_set_input_delay",
        "set_input_delay -clock [get_clocks {{{{clock}}}}] -max {{{{delay}}}} [get_ports {{{{port}}}}]",
        "Set input delay (max).",
        "constraints",
        [ArgSpec("clock"), ArgSpec("delay"), ArgSpec("port")],
    ),
    _t(
        "viv_set_output_delay",
        "set_output_delay -clock [get_clocks {{{{clock}}}}] -max {{{{delay}}}} [get_ports {{{{port}}}}]",
        "Set output delay (max).",
        "constraints",
        [ArgSpec("clock"), ArgSpec("delay"), ArgSpec("port")],
    ),
    _t(
        "viv_set_input_delay_min",
        "set_input_delay -clock [get_clocks {{{{clock}}}}] -min {{{{delay}}}} [get_ports {{{{port}}}}]",
        "Set input delay (min, hold).",
        "constraints",
        [ArgSpec("clock"), ArgSpec("delay"), ArgSpec("port")],
    ),
    _t(
        "viv_set_output_delay_min",
        "set_output_delay -clock [get_clocks {{{{clock}}}}] -min {{{{delay}}}} [get_ports {{{{port}}}}]",
        "Set output delay (min, hold).",
        "constraints",
        [ArgSpec("clock"), ArgSpec("delay"), ArgSpec("port")],
    ),
    _t(
        "viv_set_load",
        "set_load {{{{load}}}} [get_ports {{{{port}}}}]",
        "Set external load on a port.",
        "constraints",
        [ArgSpec("load"), ArgSpec("port")],
    ),
    _t(
        "viv_set_drive",
        "set_drive {{{{drive}}}} [get_ports {{{{port}}}}]",
        "Set external drive strength.",
        "constraints",
        [ArgSpec("drive"), ArgSpec("port")],
    ),
    _t(
        "viv_set_clock_uncertainty",
        "set_clock_uncertainty -setup {{{{unc}}}} [get_clocks {{{{clock}}}}]",
        "Set clock uncertainty (setup).",
        "constraints",
        [ArgSpec("unc"), ArgSpec("clock")],
    ),
    _t(
        "viv_set_clock_latency",
        "set_clock_latency -source {{{{lat}}}} [get_clocks {{{{clock}}}}]",
        "Set clock latency.",
        "constraints",
        [ArgSpec("lat"), ArgSpec("clock")],
    ),
    _t(
        "viv_set_disable_timing",
        "set_disable_timing [get_pins {{{{pin}}}}]",
        "Disable timing arcs on a pin.",
        "constraints",
        [ArgSpec("pin")],
    ),
    _t(
        "viv_set_case_analysis",
        "set_case_analysis {{{{val}}}} [get_pins {{{{pin}}}}]",
        "Apply case analysis to a pin.",
        "constraints",
        [ArgSpec("val", "0, 1, rise, fall, zero, one."), ArgSpec("pin")],
    ),
    _t(
        "viv_create_clock_waveform",
        "create_clock -name {{{{name}}}} -period {{{{period}}}} -waveform {{0 {{{{high}}}}}}",
        "Create a virtual clock (no source).",
        "constraints",
        [ArgSpec("name"), ArgSpec("period"), ArgSpec("high")],
    ),
    _t("viv_get_clocks", "get_clocks", "List all clocks.", "constraints"),
    _t(
        "viv_get_clocks_pattern",
        "get_clocks {{{{pattern}}}}",
        "List clocks matching PATTERN.",
        "constraints",
        [ArgSpec("pattern")],
    ),
    _t(
        "viv_get_generated_clocks",
        "get_clocks -generated",
        "List all generated clocks.",
        "constraints",
    ),
    _t("viv_all_clocks", "all_clocks", "Return all clocks (alias).", "constraints"),
    _t("viv_all_inputs", "all_inputs", "Return all input ports.", "constraints"),
    _t("viv_all_outputs", "all_outputs", "Return all output ports.", "constraints"),
    _t("viv_all_registers", "all_registers", "Return all registers.", "constraints"),
    _t("viv_all_ffs", "all_ffs", "Return all flip-flops.", "constraints"),
    _t("viv_all_latches", "all_latches", "Return all latches.", "constraints"),
    _t("viv_all_rams", "all_rams", "Return all RAMs.", "constraints"),
    _t("viv_all_dsps", "all_dsps", "Return all DSPs.", "constraints"),
    _t("viv_reset_timing", "reset_timing", "Reset all timing constraints.", "constraints"),
    _t(
        "viv_get_xdc_files",
        "get_files -of_objects [get_filesets constrs_1]",
        "List XDC files attached to constrs_1.",
        "constraints",
    ),
    _t(
        "viv_set_property_used_in_impl",
        "set_property used_in_implementation true [get_files {{{{file}}}}]",
        "Mark an XDC as used in impl.",
        "constraints",
        [ArgSpec("file")],
    ),
    _t(
        "viv_set_property_used_in_synth",
        "set_property used_in_synthesis true [get_files {{{{file}}}}]",
        "Mark an XDC as used in synth.",
        "constraints",
        [ArgSpec("file")],
    ),
    _t(
        "viv_set_property_late_order",
        "set_property PROCESSING_ORDER LATE [get_files {{{{file}}}}]",
        "Mark an XDC as processed late.",
        "constraints",
        [ArgSpec("file")],
    ),
    _t(
        "viv_set_property_early_order",
        "set_property PROCESSING_ORDER EARLY [get_files {{{{file}}}}]",
        "Mark an XDC as processed early.",
        "constraints",
        [ArgSpec("file")],
    ),
    _t(
        "viv_set_property_target",
        "set_property TARGET {{{{target}}}} [get_files {{{{file}}}}]",
        "Set the constraint file target (constrs_1 only).",
        "constraints",
        [ArgSpec("file"), ArgSpec("target")],
    ),
]

# ============================================================================
# Timing reports
# ============================================================================

SPECS += [
    _t(
        "viv_report_timing",
        "report_timing -return_string -max_paths {{{{n}}}} -nworst {{{{n}}}} -slack_lesser_than 0",
        "Report failing timing paths.",
        "timing_reports",
        [ArgSpec("n", "Number of paths.", required=False, default=10, type_hint=int)],
    ),
    _t(
        "viv_report_timing_summary",
        "report_timing_summary -return_string -max_paths {{{{n}}}}",
        "Report timing summary (WNS/TNS).",
        "timing_reports",
        [ArgSpec("n", required=False, default=10, type_hint=int)],
    ),
    _t(
        "viv_report_timing_max_paths",
        "report_timing -return_string -max_paths {{{{n}}}} -sort_by group",
        "Report top-N paths sorted by group.",
        "timing_reports",
        [ArgSpec("n")],
    ),
    _t(
        "viv_report_clocks",
        "report_clocks -return_string",
        "Report all clocks in the design.",
        "timing_reports",
    ),
    _t(
        "viv_report_clock_interaction",
        "report_clock_interaction -return_string",
        "Report clock-domain interactions.",
        "timing_reports",
    ),
    _t(
        "viv_report_clock_transfers",
        "report_clock_transfers -return_string",
        "Report clock-to-clock transfers.",
        "timing_reports",
    ),
    _t("viv_report_cdc", "report_cdc -return_string", "Report CDC violations.", "timing_reports"),
    _t(
        "viv_report_bus_skew",
        "report_bus_skew -return_string",
        "Report bus skew.",
        "timing_reports",
    ),
    _t(
        "viv_report_exceptions",
        "report_exceptions -return_string",
        "Report timing exceptions (false paths etc.).",
        "timing_reports",
    ),
    _t(
        "viv_report_methodology",
        "report_methodology -return_string",
        "Report methodology checks.",
        "timing_reports",
    ),
    _t(
        "viv_report_high_fanout_nets",
        "report_high_fanout_nets -return_string",
        "Report high-fanout nets.",
        "timing_reports",
    ),
    _t(
        "viv_report_clock_routing",
        "report_clock_routing -return_string",
        "Report clock routing resources.",
        "timing_reports",
    ),
    _t(
        "viv_report_route_status",
        "report_route_status -return_string",
        "Report routing status (routed/unrouted).",
        "timing_reports",
    ),
    _t(
        "viv_get_timing_paths",
        "get_timing_paths -max_paths {{{{n}}}} -slack_lesser_than 0",
        "Return failing timing paths as objects.",
        "timing_reports",
        [ArgSpec("n", required=False, default=10, type_hint=int)],
    ),
    _t(
        "viv_get_path_property",
        "get_property {{{{prop}}}} [lindex [get_timing_paths] {{{{i}}}}]",
        "Get a property on the i-th timing path.",
        "timing_reports",
        [ArgSpec("prop"), ArgSpec("i", "Path index.", type_hint=int)],
    ),
    _t(
        "viv_report_path_delay",
        "report_timing -return_string -from [get_pins {{{{from}}}}] -to [get_pins {{{{to}}}}] -max_paths 1",
        "Report delay between two specific pins.",
        "timing_reports",
        [ArgSpec("from"), ArgSpec("to")],
    ),
    _t(
        "viv_get_wns",
        "get_property SLACK [get_timing_paths -max_paths 1 -nworst 1]",
        "Get WNS as a float.",
        "timing_reports",
    ),
    _t(
        "viv_get_tns",
        "get_property TNS [get_timing_paths -max_paths 1 -nworst 1]",
        "Get TNS as a float.",
        "timing_reports",
    ),
    _t(
        "viv_report_clock_jitter",
        "report_clock_jitter -return_string",
        "Report clock jitter.",
        "timing_reports",
    ),
    _t(
        "viv_report_clock_latency",
        "report_clock_latency -return_string",
        "Report clock latency.",
        "timing_reports",
    ),
    _t(
        "viv_report_clock_groups",
        "report_clock_groups -return_string",
        "Report clock groups.",
        "timing_reports",
    ),
    _t(
        "viv_report_qor_suggestions",
        "report_qor_suggestions -return_string",
        "Report QoR optimization suggestions.",
        "timing_reports",
    ),
    _t(
        "viv_report_clock_propagation",
        "report_clock_propagation -return_string",
        "Report clock propagation tree.",
        "timing_reports",
    ),
    _t(
        "viv_report_powerup",
        "report_powerup -return_string",
        "Report power-up state of registers.",
        "timing_reports",
    ),
    _t(
        "viv_report_environment",
        "report_environment -return_string",
        "Report the environment (versions, etc.).",
        "timing_reports",
    ),
    _t(
        "viv_report_hierarchy",
        "report_hierarchy -return_string",
        "Report the design hierarchy.",
        "timing_reports",
    ),
    _t(
        "viv_report_property",
        "report_property -return_string [get_cells {{{{cell}}}}]",
        "Report all properties of a cell.",
        "timing_reports",
        [ArgSpec("cell")],
    ),
    _t(
        "viv_report_design_analysis",
        "report_design_analysis -return_string",
        "Report design analysis (congestion, depth).",
        "timing_reports",
    ),
    _t(
        "viv_report_pipeline_analysis",
        "report_pipeline_analysis -return_string",
        "Report pipeline stages in the design.",
        "timing_reports",
    ),
    _t(
        "viv_report_floorplan",
        "report_floorplan -return_string",
        "Report floorplanning.",
        "timing_reports",
    ),
]

# ============================================================================
# Utilization & DRC reports
# ============================================================================

SPECS += [
    _t(
        "viv_report_utilization",
        "report_utilization -return_string",
        "Report device utilization.",
        "utilization_reports",
    ),
    _t(
        "viv_report_utilization_hierarchical",
        "report_utilization -hierarchical -return_string",
        "Report utilization by hierarchy.",
        "utilization_reports",
    ),
    _t(
        "viv_report_utilization_slr",
        "report_utilization -slr -return_string",
        "Report utilization per SLR (SSIT only).",
        "utilization_reports",
    ),
    _t(
        "viv_report_utilization_bram",
        'report_utilization -return_string -cells [get_cells -hier -filter {{ REF_NAME =~ "*RAMB*" || REF_NAME =~ "*RAMS*" }}]',
        "Report BRAM utilization only.",
        "utilization_reports",
    ),
    _t(
        "viv_report_utilization_dsp",
        'report_utilization -return_string -cells [get_cells -hier -filter {{ REF_NAME =~ "DSP*" }}]',
        "Report DSP utilization only.",
        "utilization_reports",
    ),
    _t(
        "viv_report_drc",
        "report_drc -return_string",
        "Run design rule checks.",
        "utilization_reports",
    ),
    _t(
        "viv_report_drc_specific",
        "report_drc -checks {{{{checks}}}} -return_string",
        "Run specific DRC checks.",
        "utilization_reports",
        [ArgSpec("checks", "Tcl list of check IDs.")],
    ),
    _t(
        "viv_report_methodology_violations",
        "report_methodology -checks [get_methodology_checks -failures] -return_string",
        "Report methodology violations only.",
        "utilization_reports",
    ),
    _t(
        "viv_report_power",
        "report_power -return_string",
        "Report power consumption.",
        "utilization_reports",
    ),
    _t(
        "viv_report_power_verbose",
        "report_power -verbose -return_string",
        "Report power in detail.",
        "utilization_reports",
    ),
    _t(
        "viv_report_route_status_verbose",
        "report_route_status -return_string -detail",
        "Detailed routing status.",
        "utilization_reports",
    ),
    _t(
        "viv_report_clock_utilization",
        "report_clock_utilization -return_string",
        "Report clock-related resources.",
        "utilization_reports",
    ),
    _t(
        "viv_report_exceptions_summary",
        "report_exceptions -summary -return_string",
        "Summarize timing exceptions.",
        "utilization_reports",
    ),
    _t(
        "viv_report_failfast",
        "report_failfast -return_string",
        "Run fail-fast design checks.",
        "utilization_reports",
    ),
    _t(
        "viv_report_ram_widgets",
        "report_ram_widgets -return_string",
        "Report RAM widget usage.",
        "utilization_reports",
    ),
    _t(
        "viv_report_pin_costs",
        "report_pin_costs -return_string",
        "Report pin cost.",
        "utilization_reports",
    ),
    _t(
        "viv_report_compile_order",
        "report_compile_order -return_string",
        "Report file compile order.",
        "utilization_reports",
    ),
    _t(
        "viv_report_env",
        "report_environment -return_string",
        "Report Vivado environment (versions, install path).",
        "utilization_reports",
    ),
    _t(
        "viv_get_clocks_summary",
        "report_clocks -summary -return_string",
        "Concise clock summary.",
        "utilization_reports",
    ),
    _t(
        "viv_get_project_summary",
        "report_project -return_string",
        "Report project summary.",
        "utilization_reports",
    ),
    _t(
        "viv_report_io",
        "report_io -return_string",
        "Report I/O pin assignments.",
        "utilization_reports",
    ),
]

# ============================================================================
# Simulation
# ============================================================================

SPECS += [
    _t(
        "viv_launch_simulation",
        "launch_simulation -mode {{{{mode}}}} -type all",
        "Launch XSim.",
        "simulation",
        [
            ArgSpec(
                "mode",
                "behavioral, post-synthesis, or timing.",
                required=False,
                default="behavioral",
            )
        ],
        timeout=3600.0,
    ),
    _t(
        "viv_launch_simulation_post_synth",
        "launch_simulation -mode post-synthesis -type all",
        "Launch post-synth simulation.",
        "simulation",
        timeout=3600.0,
    ),
    _t(
        "viv_launch_simulation_timing",
        "launch_simulation -mode timing -type all",
        "Launch timing (post-impl) simulation.",
        "simulation",
        timeout=3600.0,
    ),
    _t(
        "viv_restart_simulation",
        "restart_simulation",
        "Restart the running simulation.",
        "simulation",
    ),
    _t(
        "viv_run_simulation",
        "run {{{{duration}}}}",
        "Run the simulation for a duration.",
        "simulation",
        [ArgSpec("duration", "e.g. 1000ns.")],
    ),
    _t("viv_run_all_simulation", "run all", "Run the simulation to completion.", "simulation"),
    _t("viv_step_simulation", "step", "Step one delta cycle.", "simulation"),
    _t("viv_close_simulation", "close_sim", "Close the simulation.", "simulation"),
    _t("viv_current_sim", "current_sim", "Return the current simulation handle.", "simulation"),
    _t(
        "viv_set_sim_top",
        "set_property top {{{{top}}}} [get_filesets sim_1]",
        "Set the sim_1 fileset top.",
        "simulation",
        [ArgSpec("top")],
    ),
    _t(
        "viv_set_sim_compile_order",
        "update_compile_order -fileset [get_filesets sim_1]",
        "Recompute sim_1 compile order.",
        "simulation",
    ),
    _t("viv_get_sim_state", "current_sim", "Return simulation state.", "simulation"),
    _t(
        "viv_set_sim_property",
        "set_property {{{{prop}}}} {{{{value}}}} [get_filesets sim_1]",
        "Set a sim_1 property.",
        "simulation",
        [ArgSpec("prop"), ArgSpec("value")],
    ),
    _t(
        "viv_get_sim_property",
        "get_property {{{{prop}}}} [get_filesets sim_1]",
        "Get a sim_1 property.",
        "simulation",
        [ArgSpec("prop")],
    ),
    _t(
        "viv_add_wave",
        "add_wave {{{{signal}}}}",
        "Add a signal to the wave viewer.",
        "simulation",
        [ArgSpec("signal")],
    ),
    _t(
        "viv_add_wave_divider",
        "add_wave_divider {{{{name}}}}",
        "Add a divider to the wave viewer.",
        "simulation",
        [ArgSpec("name")],
    ),
    _t(
        "viv_get_wave_objects",
        "get_wave_objects",
        "List all objects in the wave viewer.",
        "simulation",
    ),
    _t(
        "viv_force_signal",
        "force {{{{signal}}}} {{{{value}}}}",
        "Force a signal value in the simulation.",
        "simulation",
        [ArgSpec("signal"), ArgSpec("value")],
    ),
    _t(
        "viv_release_signal",
        "release {{{{signal}}}}",
        "Release a previously forced signal.",
        "simulation",
        [ArgSpec("signal")],
    ),
    _t(
        "viv_get_value",
        "get_value {{{{signal}}}}",
        "Get the current value of a signal.",
        "simulation",
        [ArgSpec("signal")],
    ),
    _t(
        "viv_set_value",
        "set_value {{{{signal}}}} {{{{value}}}}",
        "Set the value of a signal.",
        "simulation",
        [ArgSpec("signal"), ArgSpec("value")],
    ),
]

# ============================================================================
# Hardware Manager
# ============================================================================

SPECS += [
    _t("viv_open_hw_manager", "open_hw_manager", "Open the hardware manager.", "hardware"),
    _t("viv_close_hw_manager", "close_hw_manager", "Close the hardware manager.", "hardware"),
    _t("viv_open_hw_target", "open_hw_target", "Open the first available JTAG target.", "hardware"),
    _t(
        "viv_open_hw_target_named",
        "open_hw_target [get_hw_targets {{{{name}}}}]",
        "Open a specific JTAG target.",
        "hardware",
        [ArgSpec("name")],
    ),
    _t("viv_close_hw_target", "close_hw_target", "Close the open JTAG target.", "hardware"),
    _t("viv_get_hw_targets", "get_hw_targets", "List available JTAG targets.", "hardware"),
    _t("viv_get_hw_devices", "get_hw_devices", "List devices on the open target.", "hardware"),
    _t(
        "viv_get_hw_device_property",
        "get_property {{{{prop}}}} [get_hw_devices {{{{device}}}}]",
        "Get a property of a hardware device.",
        "hardware",
        [ArgSpec("device"), ArgSpec("prop")],
    ),
    _t(
        "viv_set_hw_device_program_file",
        "set_property PROGRAM.FILE {{ {{{{bit}}}} }} [get_hw_devices {{{{device}}}}]",
        "Set the bitstream file to program.",
        "hardware",
        [ArgSpec("device"), ArgSpec("bit")],
    ),
    _t(
        "viv_set_hw_device_probes_file",
        "set_property PROBES.FILE {{ {{{{ltx}}}} }} [get_hw_devices {{{{device}}}}]",
        "Set the probes (.ltx) file.",
        "hardware",
        [ArgSpec("device"), ArgSpec("ltx")],
    ),
    _t(
        "viv_program_hw_device",
        "program_hw_devices [get_hw_devices {{{{device}}}}]",
        "Program the named device.",
        "hardware",
        [ArgSpec("device")],
    ),
    _t(
        "viv_refresh_hw_device",
        "refresh_hw_device [get_hw_devices {{{{device}}}}]",
        "Refresh (re-read) the device state.",
        "hardware",
        [ArgSpec("device")],
    ),
    _t("viv_get_hw_ilas", "get_hw_ilas", "List ILA cores in the programmed device.", "hardware"),
    _t("viv_get_hw_vios", "get_hw_vios", "List VIO cores in the programmed device.", "hardware"),
    _t(
        "viv_run_hw_ila_trigger",
        "run_hw_ila [get_hw_ilas {{{{name}}}}]",
        "Arm and run an ILA trigger.",
        "hardware",
        [ArgSpec("name")],
    ),
    _t(
        "viv_run_hw_ila_capture",
        "run_hw_ila -trigger_now [get_hw_ilas {{{{name}}}}]",
        "Force-capture an ILA immediately.",
        "hardware",
        [ArgSpec("name")],
    ),
    _t(
        "viv_get_hw_ila_property",
        "get_property {{{{prop}}}} [get_hw_ilas {{{{name}}}}]",
        "Get an ILA property.",
        "hardware",
        [ArgSpec("name"), ArgSpec("prop")],
    ),
    _t(
        "viv_set_hw_ila_property",
        "set_property {{{{prop}}}} {{{{value}}}} [get_hw_ilas {{{{name}}}}]",
        "Set an ILA property (e.g. trigger position).",
        "hardware",
        [ArgSpec("name"), ArgSpec("prop"), ArgSpec("value")],
    ),
    _t(
        "viv_set_hw_ila_trigger",
        "set_property CONTROL.TRIGGER_CONDITION {{{{cond}}}} [get_hw_ilas {{{{name}}}}]",
        "Set ILA trigger condition.",
        "hardware",
        [ArgSpec("name"), ArgSpec("cond")],
    ),
    _t(
        "viv_set_hw_vio_output",
        "set_property OUTPUT_VALUE {{{{value}}}} [get_hw_probes {{{{probe}}}}]",
        "Set a VIO output probe value.",
        "hardware",
        [ArgSpec("probe"), ArgSpec("value")],
    ),
    _t(
        "viv_get_hw_vio_input",
        "get_property INPUT_VALUE [get_hw_probes {{{{probe}}}}]",
        "Read a VIO input probe value.",
        "hardware",
        [ArgSpec("probe")],
    ),
    _t(
        "viv_create_hw_probe",
        "create_hw_probe {{{{name}}}} [get_hw_devices {{{{device}}}}]",
        "Create a hw probe.",
        "hardware",
        [ArgSpec("name"), ArgSpec("device")],
    ),
    _t(
        "viv_get_hw_probes",
        "get_hw_probes [get_hw_devices {{{{device}}}}]",
        "List hw probes on a device.",
        "hardware",
        [ArgSpec("device")],
    ),
    _t(
        "viv_report_hw_target",
        "report_hw_target [get_hw_targets]",
        "Report the JTAG target info.",
        "hardware",
    ),
    _t(
        "viv_report_hw_devices",
        "report_hw_devices [get_hw_devices]",
        "Report all hardware devices.",
        "hardware",
    ),
    _t(
        "viv_write_hw_ila_data",
        "write_hw_ila_data -force {{{{path}}}} [get_hw_ilas {{{{name}}}}]",
        "Export ILA capture data to a file.",
        "hardware",
        [ArgSpec("path"), ArgSpec("name")],
    ),
    _t(
        "viv_disconnect_hw_server",
        "disconnect_hw_server",
        "Disconnect from the hw_server.",
        "hardware",
    ),
    _t(
        "viv_connect_hw_server",
        "connect_hw_server -url {{{{url}}}} -allow_non_jtag",
        "Connect to a remote hw_server.",
        "hardware",
        [ArgSpec("url", "e.g. tcp:host:3121.")],
    ),
]

# ============================================================================
# Debug cores (ILA / VIO / IBERT)
# ============================================================================

SPECS += [
    _t(
        "viv_create_debug_core",
        "create_debug_core [get_ips {{{{ip}}}}]",
        "Create a debug core.",
        "debug",
    ),
    _t(
        "viv_set_debug_core_property",
        "set_property {{{{prop}}}} {{{{value}}}} [get_debug_cores {{{{name}}}}]",
        "Set a debug core property.",
        "debug",
        [ArgSpec("name"), ArgSpec("prop"), ArgSpec("value")],
    ),
    _t("viv_get_debug_cores", "get_debug_cores", "List debug cores in the design.", "debug"),
    _t(
        "viv_connect_debug_port",
        "connect_debug_port [get_debug_ports {{{{port}}}}] [get_nets {{{{net}}}}]",
        "Connect a debug port to a net.",
        "debug",
        [ArgSpec("port"), ArgSpec("net")],
    ),
    _t(
        "viv_disconnect_debug_port",
        "disconnect_debug_port [get_debug_ports {{{{port}}}}]",
        "Disconnect a debug port.",
        "debug",
        [ArgSpec("port")],
    ),
    _t("viv_get_debug_ports", "get_debug_ports", "List all debug ports.", "debug"),
    _t(
        "viv_set_debug_port_property",
        "set_property {{{{prop}}}} {{{{value}}}} [get_debug_ports {{{{port}}}}]",
        "Set a debug port property.",
        "debug",
        [ArgSpec("port"), ArgSpec("prop"), ArgSpec("value")],
    ),
    _t(
        "viv_set_debug_port_width",
        "set_property PORT_WIDTH {{{{width}}}} [get_debug_ports {{{{port}}}}]",
        "Set the width of a debug port.",
        "debug",
        [ArgSpec("port"), ArgSpec("width", "Bit width.", type_hint=int)],
    ),
    _t(
        "viv_set_probe_clk",
        "set_property C_INPUT_PIPE_STAGES 1 [get_debug_ports {{{{port}}}}]",
        "Set input pipeline stages on a probe.",
        "debug",
        [ArgSpec("port")],
    ),
    _t(
        "viv_set_trigger_compare_value",
        "set_property COMPARE_VALUE {{{{value}}}} [get_debug_ports {{{{port}}}}]",
        "Set a probe trigger compare value.",
        "debug",
        [ArgSpec("port"), ArgSpec("value")],
    ),
    _t(
        "viv_set_trigger_position",
        "set_property CONTROL.TRIGGER_POSITION {{{{pos}}}} [get_hw_ilas {{{{name}}}}]",
        "Set the ILA trigger position (samples before trigger).",
        "debug",
        [ArgSpec("name"), ArgSpec("pos", type_hint=int)],
    ),
    _t(
        "viv_set_capture_mode",
        "set_property CONTROL.CAPTURE_MODE {{{{mode}}}} [get_hw_ilas {{{{name}}}}]",
        "Set ILA capture mode (BASIC/ADVANCED).",
        "debug",
        [ArgSpec("name"), ArgSpec("mode")],
    ),
    _t(
        "viv_implement_debug_core",
        "implement_debug_core",
        "Run the debug core implementation step.",
        "debug",
    ),
    _t(
        "viv_save_debug_core",
        "save_debug_core [get_debug_cores {{{{name}}}}]",
        "Save a debug core config.",
        "debug",
        [ArgSpec("name")],
    ),
    _t(
        "viv_create_ila_ip",
        "create_ip -name ila -version 6.2 -module_name {{{{name}}}}",
        "Create an ILA IP instance.",
        "debug",
        [ArgSpec("name")],
    ),
    _t(
        "viv_create_vio_ip",
        "create_ip -name vio -version 3.0 -module_name {{{{name}}}}",
        "Create a VIO IP instance.",
        "debug",
        [ArgSpec("name")],
    ),
]

# ============================================================================
# Netlist queries (cells / nets / pins / ports / bels)
# ============================================================================

SPECS += [
    _t("viv_get_cells", "get_cells", "List all cells in the open design.", "netlist"),
    _t(
        "viv_get_cells_pattern",
        "get_cells {{{{pattern}}}} -hier",
        "List cells matching PATTERN.",
        "netlist",
        [ArgSpec("pattern")],
    ),
    _t(
        "viv_get_cells_of_ref",
        "get_cells -hier -filter {{ REF_NAME =~ {{{{ref}}}} }}",
        "List cells of a specific ref (e.g. LUT6).",
        "netlist",
        [ArgSpec("ref")],
    ),
    _t("viv_get_nets", "get_nets", "List all nets.", "netlist"),
    _t(
        "viv_get_nets_pattern",
        "get_nets {{{{pattern}}}} -hier",
        "List nets matching PATTERN.",
        "netlist",
        [ArgSpec("pattern")],
    ),
    _t("viv_get_pins", "get_pins", "List all pins.", "netlist"),
    _t(
        "viv_get_pins_of_cell",
        "get_pins -of_objects [get_cells {{{{cell}}}}]",
        "List pins of a cell.",
        "netlist",
        [ArgSpec("cell")],
    ),
    _t("viv_get_ports", "get_ports", "List all ports.", "netlist"),
    _t(
        "viv_get_ports_pattern",
        "get_ports {{{{pattern}}}}",
        "List ports matching PATTERN.",
        "netlist",
        [ArgSpec("pattern")],
    ),
    _t("viv_get_lib_cells", "get_lib_cells", "List all library cells.", "netlist"),
    _t(
        "viv_get_lib_cell_pins",
        "get_lib_cells -of_objects [get_libs {{{{lib}}}}]",
        "List lib cells of a lib.",
        "netlist",
        [ArgSpec("lib")],
    ),
    _t("viv_get_libs", "get_libs", "List all libraries.", "netlist"),
    _t(
        "viv_get_libs_pattern",
        "get_libs {{{{pattern}}}}",
        "List libs matching PATTERN.",
        "netlist",
        [ArgSpec("pattern")],
    ),
    _t("viv_get_bels", "get_bels", "List bels (placed design only).", "netlist"),
    _t(
        "viv_get_bels_of_cell",
        "get_bels -of_objects [get_cells {{{{cell}}}}]",
        "List bels of a placed cell.",
        "netlist",
        [ArgSpec("cell")],
    ),
    _t("viv_get_sites", "get_sites", "List all sites on the device.", "netlist"),
    _t(
        "viv_get_site_property",
        "get_property {{{{prop}}}} [get_sites {{{{site}}}}]",
        "Get a property of a site.",
        "netlist",
        [ArgSpec("site"), ArgSpec("prop")],
    ),
    _t("viv_get_pblocks", "get_pblocks", "List all pblocks.", "netlist"),
    _t(
        "viv_create_pblock",
        "create_pblock {{{{name}}}}",
        "Create a pblock.",
        "netlist",
        [ArgSpec("name")],
    ),
    _t(
        "viv_delete_pblock",
        "delete_pblocks [get_pblocks {{{{name}}}}]",
        "Delete a pblock.",
        "netlist",
        [ArgSpec("name")],
    ),
    _t(
        "viv_resize_pblock",
        "resize_pblock [get_pblocks {{{{name}}}}] -add {{{{sites}}}}",
        "Add sites to a pblock.",
        "netlist",
        [ArgSpec("name"), ArgSpec("sites")],
    ),
    _t(
        "viv_add_cells_to_pblock",
        "add_cells_to_pblock [get_pblocks {{{{name}}}}] [get_cells {{{{cells}}}}]",
        "Add cells to a pblock.",
        "netlist",
        [ArgSpec("name"), ArgSpec("cells")],
    ),
    _t(
        "viv_get_cell_property",
        "get_property {{{{prop}}}} [get_cells {{{{cell}}}}]",
        "Get a property of a cell.",
        "netlist",
        [ArgSpec("cell"), ArgSpec("prop")],
    ),
    _t(
        "viv_set_cell_property",
        "set_property {{{{prop}}}} {{{{value}}}} [get_cells {{{{cell}}}}]",
        "Set a property of a cell.",
        "netlist",
        [ArgSpec("cell"), ArgSpec("prop"), ArgSpec("value")],
    ),
    _t(
        "viv_get_net_property",
        "get_property {{{{prop}}}} [get_nets {{{{net}}}}]",
        "Get a property of a net.",
        "netlist",
        [ArgSpec("net"), ArgSpec("prop")],
    ),
    _t(
        "viv_set_net_property",
        "set_property {{{{prop}}}} {{{{value}}}} [get_nets {{{{net}}}}]",
        "Set a property of a net.",
        "netlist",
        [ArgSpec("net"), ArgSpec("prop"), ArgSpec("value")],
    ),
    _t(
        "viv_get_pin_property",
        "get_property {{{{prop}}}} [get_pins {{{{pin}}}}]",
        "Get a property of a pin.",
        "netlist",
        [ArgSpec("pin"), ArgSpec("prop")],
    ),
    _t(
        "viv_get_port_property",
        "get_property {{{{prop}}}} [get_ports {{{{port}}}}]",
        "Get a property of a port.",
        "netlist",
        [ArgSpec("port"), ArgSpec("prop")],
    ),
    _t(
        "viv_set_property_async_reg",
        "set_property ASYNC_REG true [get_cells -hier -filter {{ NAME =~ {{{{name}}}} }}]",
        "Mark a register as async (CDC) — important for 2-FF synchronizers.",
        "netlist",
        [ArgSpec("name")],
    ),
    _t(
        "viv_set_property_dont_touch",
        "set_property DONT_TOUCH true [get_cells {{{{cell}}}}]",
        "Prevent optimization on a cell.",
        "netlist",
        [ArgSpec("cell")],
    ),
    _t(
        "viv_set_property_use_dsp48",
        "set_property USE_DSP48 yes [get_cells -hier -filter {{ NAME =~ {{{{name}}}} }}]",
        "Hint that a multiply should use DSP48.",
        "netlist",
        [ArgSpec("name")],
    ),
]

# ============================================================================
# Parts / devices / boards
# ============================================================================

SPECS += [
    _t("viv_get_parts", "get_parts", "List all available parts.", "parts"),
    _t(
        "viv_get_parts_pattern",
        "get_parts {{{{pattern}}}}",
        "List parts matching PATTERN.",
        "parts",
        [ArgSpec("pattern")],
    ),
    _t(
        "viv_get_part_property",
        "get_property {{{{prop}}}} [get_parts {{{{part}}}}]",
        "Get a property of a part.",
        "parts",
        [ArgSpec("part"), ArgSpec("prop")],
    ),
    _t(
        "viv_get_part_packages",
        "get_property PACKAGE_PIN_COUNT [get_parts {{{{part}}}}]",
        "Get the package pin count for a part.",
        "parts",
        [ArgSpec("part")],
    ),
    _t("viv_get_families", "get_part_families", "List FPGA families.", "parts"),
    _t("viv_get_boards", "get_boards", "List known board files.", "parts"),
    _t(
        "viv_get_boards_pattern",
        "get_boards {{{{pattern}}}}",
        "List boards matching PATTERN.",
        "parts",
        [ArgSpec("pattern")],
    ),
    _t(
        "viv_get_board_property",
        "get_property {{{{prop}}}} [get_boards {{{{board}}}}]",
        "Get a property of a board.",
        "parts",
        [ArgSpec("board"), ArgSpec("prop")],
    ),
    _t(
        "viv_get_board_part",
        "get_property PART [get_boards {{{{board}}}}]",
        "Get the part of a board.",
        "parts",
        [ArgSpec("board")],
    ),
    _t(
        "viv_get_package_pins",
        "get_package_pins -of_objects [get_ports {{{{port}}}}]",
        "Get package pins of a port.",
        "parts",
        [ArgSpec("port")],
    ),
    _t("viv_get_iobanks", "get_iobanks", "List all I/O banks on the part.", "parts"),
    _t(
        "viv_get_iobanks_of_port",
        "get_iobanks -of_objects [get_ports {{{{port}}}}]",
        "Get I/O bank of a port.",
        "parts",
        [ArgSpec("port")],
    ),
    _t(
        "viv_get_package_pin_property",
        "get_property {{{{prop}}}} [get_package_pins {{{{pin}}}}]",
        "Get a property of a package pin.",
        "parts",
        [ArgSpec("pin"), ArgSpec("prop")],
    ),
    _t(
        "viv_set_property_package_pin",
        "set_property PACKAGE_PIN {{{{pin}}}} [get_ports {{{{port}}}}]",
        "Assign a package pin to a port.",
        "parts",
        [ArgSpec("port"), ArgSpec("pin")],
    ),
    _t(
        "viv_set_property_io_standard",
        "set_property IOSTANDARD {{{{standard}}}} [get_ports {{{{port}}}}]",
        "Set IOSTANDARD for a port.",
        "parts",
        [ArgSpec("port"), ArgSpec("standard")],
    ),
    _t(
        "viv_set_property_slew",
        "set_property SLEW {{{{slew}}}} [get_ports {{{{port}}}}]",
        "Set slew rate.",
        "parts",
        [ArgSpec("port"), ArgSpec("slew", "SLOW or FAST.")],
    ),
    _t(
        "viv_set_property_drive",
        "set_property DRIVE {{{{drive}}}} [get_ports {{{{port}}}}]",
        "Set drive strength (mA).",
        "parts",
        [ArgSpec("port"), ArgSpec("drive")],
    ),
    _t(
        "viv_set_property_pullup",
        "set_property PULLUP true [get_ports {{{{port}}}}]",
        "Enable pull-up resistor.",
        "parts",
        [ArgSpec("port")],
    ),
    _t(
        "viv_set_property_pulldown",
        "set_property PULLDOWN true [get_ports {{{{port}}}}]",
        "Enable pull-down resistor.",
        "parts",
        [ArgSpec("port")],
    ),
]

# ============================================================================
# Tcl-level / scripting helpers
# ============================================================================

SPECS += [
    _t(
        "viv_source_tcl",
        "source {{{{file}}}}",
        "Source a Tcl file inside the Vivado session.",
        "tcl",
        [ArgSpec("file")],
    ),
    _t(
        "viv_puts",
        "puts {{{{message}}}}",
        "Print a message to the Vivado console.",
        "tcl",
        [ArgSpec("message")],
    ),
    _t(
        "viv_set_var",
        "set {{{{name}}}} {{{{value}}}}",
        "Set a Tcl variable in the session.",
        "tcl",
        [ArgSpec("name"), ArgSpec("value")],
    ),
    _t("viv_get_var", "set {{{{name}}}}", "Get a Tcl variable's value.", "tcl", [ArgSpec("name")]),
    _t(
        "viv_set_env",
        "set ::env({{{{name}}}}) {{{{value}}}}",
        "Set an environment variable.",
        "tcl",
        [ArgSpec("name"), ArgSpec("value")],
    ),
    _t(
        "viv_get_env",
        "return $::env({{{{name}}}})",
        "Get an environment variable.",
        "tcl",
        [ArgSpec("name")],
    ),
    _t("viv_pwd", "pwd", "Return the current working directory.", "tcl"),
    _t("viv_cd", "cd {{{{dir}}}}", "Change the working directory.", "tcl", [ArgSpec("dir")]),
    _t(
        "viv_list_dir",
        "glob -nocomplain -directory {{{{dir}}}} *",
        "List files in a directory.",
        "tcl",
        [ArgSpec("dir")],
    ),
    _t(
        "viv_file_exists",
        "file exists {{{{path}}}}",
        "Return 1 if PATH exists.",
        "tcl",
        [ArgSpec("path")],
    ),
    _t(
        "viv_file_stat",
        "file stat {{{{path}}}} arr; return $arr(size)",
        "Get the size of a file.",
        "tcl",
        [ArgSpec("path")],
    ),
    _t(
        "viv_file_mtime",
        "file mtime {{{{path}}}}",
        "Get the modification time of a file.",
        "tcl",
        [ArgSpec("path")],
    ),
    _t(
        "viv_exec",
        "exec {{{{{command}}}}} >&@stdout",
        "Run a system command inside the Vivado session.",
        "tcl",
        [ArgSpec("command")],
    ),
    _t(
        "viv_catch",
        "catch {{{{cmd}}}} result; return $result",
        "Catch an error from a Tcl command.",
        "tcl",
        [ArgSpec("cmd")],
    ),
    _t(
        "viv_info",
        "send_msg_id {{{{id}}}} INFO {{{{message}}}}",
        "Log an INFO message.",
        "tcl",
        [ArgSpec("id"), ArgSpec("message")],
    ),
    _t(
        "viv_warning",
        "send_msg_id {{{{id}}}} WARNING {{{{message}}}}",
        "Log a WARNING message.",
        "tcl",
        [ArgSpec("id"), ArgSpec("message")],
    ),
    _t(
        "viv_error_msg",
        "send_msg_id {{{{id}}}} ERROR {{{{message}}}}",
        "Log an ERROR message.",
        "tcl",
        [ArgSpec("id"), ArgSpec("message")],
    ),
    _t(
        "viv_puts_log",
        "puts -nonewline [open {{{{path}}}} a] {{{{message}}}}\\n; close $fd",
        "Append a message to a log file.",
        "tcl",
        [ArgSpec("path"), ArgSpec("message")],
    ),
    _t("viv_get_vivado_version", "version -short", "Return the Vivado version string.", "tcl"),
    _t(
        "viv_get_vivado_install_dir",
        "return $::env(XILINX_VIVADO)",
        "Return the Vivado install directory.",
        "tcl",
    ),
    _t("viv_get_user_id", "return $::env(USER)", "Return the current user name.", "tcl"),
]

# ============================================================================
# Linting & Code Quality (SynthPilot Pro parity)
# ============================================================================

SPECS += [
    _t(
        "viv_lint_syntax",
        "check_syntax -return_string",
        "Check HDL syntax for all source files.",
        "lint",
    ),
    _t(
        "viv_lint_methodology",
        "report_methodology -return_string",
        "Run methodology checks (UltraFast design methodology).",
        "lint",
    ),
    _t(
        "viv_lint_cdc",
        "report_cdc -return_string",
        "Run Clock Domain Crossing (CDC) analysis.",
        "lint",
    ),
    _t(
        "viv_lint_drc",
        "report_drc -return_string",
        "Run Design Rule Check (DRC).",
        "lint",
    ),
    _t(
        "viv_lint_noise",
        "report_ssn -return_string",
        "Run Simultaneous Switching Noise (SSN) analysis.",
        "lint",
    ),
    _t(
        "viv_lint_clock_interaction",
        "report_clock_interaction -return_string",
        "Report clock domain interactions and CDC paths.",
        "lint",
    ),
    _t(
        "viv_lint_pulse_width",
        "report_pulse_width -return_string",
        "Check minimum pulse width requirements.",
        "lint",
    ),
    _t(
        "viv_lint_exceptions",
        "report_exceptions -return_string",
        "Report timing exceptions (false path, multicycle, etc.).",
        "lint",
    ),
    _t(
        "viv_lint_case_analysis",
        "report_case_analysis -return_string",
        "Report case analysis settings.",
        "lint",
    ),
    _t(
        "viv_lint_bus_skew",
        "report_bus_skew -return_string",
        "Report bus skew analysis.",
        "lint",
    ),
    _t(
        "viv_lint_synchronizer",
        "report_synchronizer -return_string",
        "Report synchronizer usage for CDC.",
        "lint",
    ),
    _t(
        "viv_lint_data_check",
        "report_data_check -return_string",
        "Report data check analysis.",
        "lint",
    ),
    _t(
        "viv_lint_disable_timing",
        "report_disable_timing -return_string",
        "Report disabled timing paths.",
        "lint",
    ),
    _t(
        "viv_lint_clock_networks",
        "report_clock_networks -return_string",
        "Report clock network analysis.",
        "lint",
    ),
    _t(
        "viv_lint_clock_utilization",
        "report_clock_utilization -return_string",
        "Report clock resource utilization.",
        "lint",
    ),
    _t(
        "viv_lint_high_fanout_nets",
        "report_high_fanout_nets -return_string -load_types -timing -max_nets 50",
        "Report high fanout nets.",
        "lint",
    ),
    _t(
        "viv_lint_route_status",
        "report_route_status -return_string",
        "Report routing status and congestion.",
        "lint",
    ),
    _t(
        "viv_lint_design_analysis",
        "report_design_analysis -return_string -complexity",
        "Report design complexity and resource analysis.",
        "lint",
    ),
    _t(
        "viv_lint_qor_suggestions",
        "report_qor_suggestions -return_string",
        "Report QoR suggestions for timing closure.",
        "lint",
    ),
    _t(
        "viv_lint_power",
        "report_power -return_string",
        "Report power estimation and analysis.",
        "lint",
    ),
    _t(
        "viv_lint_io",
        "report_io -return_string",
        "Report I/O planning and constraints.",
        "lint",
    ),
    _t(
        "viv_lint_primitives",
        "report_primitives -return_string",
        "Report primitive usage in the design.",
        "lint",
    ),
    _t(
        "viv_lint_ram_utilization",
        "report_ram_utilization -return_string",
        "Report RAM/BRAM utilization details.",
        "lint",
    ),
    _t(
        "viv_lint_slr_utilization",
        "report_slr_utilization -return_string",
        "Report SLR (Super Logic Region) utilization (SSI devices).",
        "lint",
    ),
    _t(
        "viv_lint_incremental_reuse",
        "report_incremental_reuse -return_string",
        "Report incremental implementation reuse statistics.",
        "lint",
    ),
    _t(
        "viv_lint_config_timing",
        "config_timing_analysis -severity {{{{severity}}}} -msg_limit {{{{limit}}}}",
        "Configure timing analysis severity and message limits.",
        "lint",
        [
            ArgSpec("severity", "INFO/WARNING/ERROR/CRITICAL"),
            ArgSpec("limit", "Max messages.", type_hint=int),
        ],
    ),
    _t(
        "viv_lint_config_drc",
        "config_drc_rules -severity {{{{severity}}}} -msg_limit {{{{limit}}}}",
        "Configure DRC rule severity.",
        "lint",
        [
            ArgSpec("severity", "INFO/WARNING/ERROR/CRITICAL"),
            ArgSpec("limit", "Max messages.", type_hint=int),
        ],
    ),
    _t(
        "viv_lint_config_methodology",
        "config_msg -severity {{{{severity}}}} -msg_limit {{{{limit}}}} -id {{{{id}}}}",
        "Configure methodology check severity.",
        "lint",
        [
            ArgSpec("id", "Message ID."),
            ArgSpec("severity", "INFO/WARNING/ERROR/CRITICAL"),
            ArgSpec("limit", "Max messages.", type_hint=int),
        ],
    ),
    _t(
        "viv_lint_waiver_add",
        "create_waive -user {{{{user}}}} -type {{{{type}}}} -description {{{{description}}}}",
        "Add a lint/DRC/methodology waiver.",
        "lint",
        [
            ArgSpec("user", "Waiver author."),
            ArgSpec("type", "DRC/METHODOLOGY/TIMING."),
            ArgSpec("description", "Waiver reason."),
        ],
    ),
    _t(
        "viv_lint_waiver_list",
        "report_waivers -return_string",
        "List all active waivers.",
        "lint",
    ),
]

# ============================================================================
# Flash Programming (SynthPilot Pro parity)
# ============================================================================

SPECS += [
    _t(
        "viv_add_flash_config",
        "create_hw_cfgmem -hw_device [current_hw_device] -mem_device {{{{flash_part}}}}",
        "Add flash memory configuration to hardware device.",
        "flash",
        [ArgSpec("flash_part", "Flash part number, e.g. s25fl128sxxxxxx0-spi-x1_x2_x4.")],
    ),
    _t(
        "viv_program_flash",
        "program_hw_cfgmem -hw_cfgmem [get_property PROGRAM.HW_CFGMEM [current_hw_device]]",
        "Program the configuration flash memory.",
        "flash",
    ),
    _t(
        "viv_generate_mcs",
        "write_cfgmem -format mcs -size {{{{size}}}} -interface {{{{interface}}}} -loadbit {{{{loadbit}}}} {{{{mcs_file}}}}",
        "Generate an MCS flash configuration file.",
        "flash",
        [
            ArgSpec("mcs_file", "Output MCS file path."),
            ArgSpec("size", "Flash size in MB."),
            ArgSpec("interface", "SPIx1/SPIx2/SPIx4/BPIx8."),
            ArgSpec("loadbit", "Bitstream file path.", required=False, default=""),
        ],
    ),
    _t(
        "viv_erase_flash",
        "erase_hw_cfgmem -hw_cfgmem [get_property PROGRAM.HW_CFGMEM [current_hw_device]]",
        "Erase the configuration flash memory.",
        "flash",
    ),
    _t(
        "viv_verify_flash",
        "verify_hw_cfgmem -hw_cfgmem [get_property PROGRAM.HW_CFGMEM [current_hw_device]]",
        "Verify flash contents against expected data.",
        "flash",
    ),
    _t(
        "viv_readback_flash",
        "readback_hw_cfgmem -hw_cfgmem [get_property PROGRAM.HW_CFGMEM [current_hw_device]] -file {{{{file}}}}",
        "Read back flash contents to a file.",
        "flash",
        [ArgSpec("file", "Output file path.")],
    ),
    _t(
        "viv_list_flash_parts",
        "get_cfgmem_parts",
        "List supported flash memory parts.",
        "flash",
    ),
    _t(
        "viv_set_flash_property",
        "set_property PROGRAM.ADDRESS_RANGE {{{{range}}}} [current_hw_device]",
        "Set flash programming address range.",
        "flash",
        [ArgSpec("range", "Address range, e.g. {0x00000000 0x00FFFFFF}.")],
    ),
]

# ============================================================================
# XSCT Embedded Development (SynthPilot Pro parity)
# ============================================================================

SPECS += [
    # --- Workspace ---
    _t(
        "viv_xsct_set_workspace",
        "setws {{{{workspace}}}}",
        "Set the XSCT workspace directory.",
        "xsct",
        [ArgSpec("workspace", "Path to workspace.")],
    ),
    _t(
        "viv_xsct_create_workspace",
        "setws -new {{{{workspace}}}}",
        "Create a new XSCT workspace.",
        "xsct",
        [ArgSpec("workspace", "Path to workspace.")],
    ),
    _t(
        "viv_xsct_get_workspace",
        "getws",
        "Get the current XSCT workspace.",
        "xsct",
    ),
    # --- Platform / BSP ---
    _t(
        "viv_xsct_create_platform",
        "platform create -name {{{{name}}}} -hw {{{{hw_file}}}} -proc {{{{processor}}}} -os {{{{os}}}}",
        "Create a platform project from hardware definition.",
        "xsct",
        [
            ArgSpec("name", "Platform name."),
            ArgSpec("hw_file", "Path to .xsa hardware file."),
            ArgSpec("processor", "Processor name, e.g. ps7_cortexa9_0."),
            ArgSpec("os", "Operating system, e.g. standalone."),
        ],
    ),
    _t(
        "viv_xsct_build_platform",
        "platform generate {{{{name}}}}",
        "Build the platform project.",
        "xsct",
        [ArgSpec("name", "Platform name.")],
    ),
    _t(
        "viv_xsct_clean_platform",
        "platform clean {{{{name}}}}",
        "Clean the platform project.",
        "xsct",
        [ArgSpec("name", "Platform name.")],
    ),
    _t(
        "viv_xsct_list_platforms",
        "platform list",
        "List all platform projects.",
        "xsct",
    ),
    _t(
        "viv_xsct_get_platform_info",
        "platform report {{{{name}}}}",
        "Get platform project information.",
        "xsct",
        [ArgSpec("name", "Platform name.")],
    ),
    _t(
        "viv_xsct_create_bsp",
        "bsp create -name {{{{name}}}} -proc {{{{processor}}}} -hwproject {{{{hwproject}}}} -os {{{{os}}}}",
        "Create a Board Support Package.",
        "xsct",
        [
            ArgSpec("name", "BSP name."),
            ArgSpec("processor", "Processor instance."),
            ArgSpec("hwproject", "Hardware project name."),
            ArgSpec("os", "OS name, e.g. standalone."),
        ],
    ),
    _t(
        "viv_xsct_set_bsp_config",
        "bsp config -name {{{{name}}}} -option {{{{option}}}} -value {{{{value}}}}",
        "Set a BSP configuration option.",
        "xsct",
        [
            ArgSpec("name", "BSP name."),
            ArgSpec("option", "Config option name."),
            ArgSpec("value", "Config value."),
        ],
    ),
    _t(
        "viv_xsct_regen_bsp",
        "bsp regenerate {{{{name}}}}",
        "Regenerate the BSP sources.",
        "xsct",
        [ArgSpec("name", "BSP name.")],
    ),
    # --- Application ---
    _t(
        "viv_xsct_create_app",
        "app create -name {{{{name}}}} -platform {{{{platform}}}} -proc {{{{processor}}}} -os {{{{os}}}} -template {{{{template}}}}",
        "Create an application project.",
        "xsct",
        [
            ArgSpec("name", "Application name."),
            ArgSpec("platform", "Platform name."),
            ArgSpec("processor", "Processor instance."),
            ArgSpec("os", "OS name."),
            ArgSpec("template", "Application template, e.g. Hello World."),
        ],
    ),
    _t(
        "viv_xsct_build_app",
        "app build {{{{name}}}}",
        "Build the application project.",
        "xsct",
        [ArgSpec("name", "Application name.")],
    ),
    _t(
        "viv_xsct_clean_app",
        "app clean {{{{name}}}}",
        "Clean the application project.",
        "xsct",
        [ArgSpec("name", "Application name.")],
    ),
    _t(
        "viv_xsct_list_apps",
        "app list",
        "List all application projects.",
        "xsct",
    ),
    _t(
        "viv_xsct_get_app_config",
        "app config -name {{{{name}}}} -get",
        "Get application build configuration.",
        "xsct",
        [ArgSpec("name", "Application name.")],
    ),
    _t(
        "viv_xsct_set_app_config",
        "app config -name {{{{name}}}} -set {{{{option}}}} {{{{value}}}}",
        "Set application build configuration.",
        "xsct",
        [
            ArgSpec("name", "Application name."),
            ArgSpec("option", "Config option."),
            ArgSpec("value", "Config value."),
        ],
    ),
    # --- Hardware download ---
    _t(
        "viv_xsct_download_bitstream",
        "fpga -file {{{{bitstream}}}} -no-revision-check",
        "Download bitstream to FPGA via JTAG.",
        "xsct",
        [ArgSpec("bitstream", "Path to .bit file.")],
    ),
    _t(
        "viv_xsct_download_elf",
        "dow {{{{elf_file}}}}",
        "Download ELF file to target processor.",
        "xsct",
        [ArgSpec("elf_file", "Path to .elf file.")],
    ),
    _t(
        "viv_xsct_run_elf",
        "con",
        "Continue execution (run the downloaded ELF).",
        "xsct",
    ),
    _t(
        "viv_xsct_stop_elf",
        "stop",
        "Stop processor execution.",
        "xsct",
    ),
    _t(
        "viv_xsct_reset_processor",
        "rst -processor",
        "Reset the target processor.",
        "xsct",
    ),
    _t(
        "viv_xsct_reset_system",
        "rst -system",
        "Reset the entire system (processor + peripherals).",
        "xsct",
    ),
    # --- Debug ---
    _t(
        "viv_xsct_set_breakpoint",
        "bpadd -addr &{{{{function}}}}",
        "Set a breakpoint at a function.",
        "xsct",
        [ArgSpec("function", "Function name.")],
    ),
    _t(
        "viv_xsct_set_breakpoint_line",
        "bpadd -file {{{{file}}}} -line {{{{line}}}}",
        "Set a breakpoint at a specific line.",
        "xsct",
        [ArgSpec("file", "Source file."), ArgSpec("line", "Line number.", type_hint=int)],
    ),
    _t(
        "viv_xsct_remove_breakpoint",
        "bpremove {{{{id}}}}",
        "Remove a breakpoint by ID.",
        "xsct",
        [ArgSpec("id", "Breakpoint ID.", type_hint=int)],
    ),
    _t(
        "viv_xsct_list_breakpoints",
        "bplist",
        "List all breakpoints.",
        "xsct",
    ),
    _t(
        "viv_xsct_step",
        "step",
        "Step into (single step).",
        "xsct",
    ),
    _t(
        "viv_xsct_next",
        "next",
        "Step over (next line).",
        "xsct",
    ),
    _t(
        "viv_xsct_finish",
        "finish",
        "Step out of current function.",
        "xsct",
    ),
    _t(
        "viv_xsct_backtrace",
        "bt",
        "Show call stack backtrace.",
        "xsct",
    ),
    _t(
        "viv_xsct_get_registers",
        "rrd",
        "Read all processor registers.",
        "xsct",
    ),
    _t(
        "viv_xsct_get_register",
        "rrd {{{{register}}}}",
        "Read a specific register.",
        "xsct",
        [ArgSpec("register", "Register name, e.g. r0/pc.")],
    ),
    _t(
        "viv_xsct_set_register",
        "mwr -force [lindex [getmem {{{{register}}}}] 0] {{{{value}}}}",
        "Write a value to a register.",
        "xsct",
        [ArgSpec("register", "Register name."), ArgSpec("value", "Value to write.")],
    ),
    _t(
        "viv_xsct_read_memory",
        "mrd -force {{{{address}}}} {{{{count}}}}",
        "Read memory at address.",
        "xsct",
        [ArgSpec("address", "Memory address."), ArgSpec("count", "Word count.", type_hint=int)],
    ),
    _t(
        "viv_xsct_write_memory",
        "mwr -force {{{{address}}}} {{{{value}}}}",
        "Write value to memory address.",
        "xsct",
        [ArgSpec("address", "Memory address."), ArgSpec("value", "Value to write.")],
    ),
    _t(
        "viv_xsct_get_locals",
        "locals",
        "List local variables in current scope.",
        "xsct",
    ),
    _t(
        "viv_xsct_get_global",
        "print {{{{variable}}}}",
        "Print value of a global/static variable.",
        "xsct",
        [ArgSpec("variable", "Variable name.")],
    ),
    # --- JTAG / Serial ---
    _t(
        "viv_xsct_list_targets",
        "targets",
        "List all JTAG targets.",
        "xsct",
    ),
    _t(
        "viv_xsct_select_target",
        "targets {{{{id}}}}",
        "Select a JTAG target by ID.",
        "xsct",
        [ArgSpec("id", "Target ID.", type_hint=int)],
    ),
    _t(
        "viv_xsct_get_target_info",
        'targets -set -nocase -filter {{name =~ "*{target}*"}}',
        "Get target information.",
        "xsct",
        [ArgSpec("target", "Target name filter.")],
    ),
    _t(
        "viv_xsct_jtag_sequence",
        "jtag sequence {{{{sequence}}}}",
        "Execute a JTAG sequence.",
        "xsct",
        [ArgSpec("sequence", "JTAG sequence string.")],
    ),
    _t(
        "viv_xsct_jtag_drscan",
        "jtag drscan {{{{device}}}} {{{{register}}}} {{{{value}}}}",
        "Perform JTAG DR scan.",
        "xsct",
        [
            ArgSpec("device", "Device index."),
            ArgSpec("register", "Register name."),
            ArgSpec("value", "Value to scan."),
        ],
    ),
    _t(
        "viv_xsct_jtag_irscan",
        "jtag irscan {{{{device}}}} {{{{instruction}}}}",
        "Perform JTAG IR scan.",
        "xsct",
        [ArgSpec("device", "Device index."), ArgSpec("instruction", "Instruction value.")],
    ),
    _t(
        "viv_xsct_open_serial",
        "set com [jtagterminal -start {{{{port}}}}]",
        "Open a JTAG UART terminal.",
        "xsct",
        [ArgSpec("port", "COM port name.")],
    ),
    _t(
        "viv_xsct_close_serial",
        "jtagterminal -stop",
        "Close the JTAG UART terminal.",
        "xsct",
    ),
    _t(
        "viv_xsct_read_serial",
        "jtagterminal -get {{{{length}}}}",
        "Read bytes from JTAG UART.",
        "xsct",
        [ArgSpec("length", "Bytes to read.", type_hint=int)],
    ),
    _t(
        "viv_xsct_write_serial",
        "jtagterminal -put {{{{data}}}}",
        "Write bytes to JTAG UART.",
        "xsct",
        [ArgSpec("data", "Data string to write.")],
    ),
    # --- HSI (Hardware Software Interface) ---
    _t(
        "viv_xsct_hsi_open_hw",
        "hsi open_hw_design {{{{hw_file}}}}",
        "Open hardware design for HSI queries.",
        "xsct",
        [ArgSpec("hw_file", "Path to .xsa file.")],
    ),
    _t(
        "viv_xsct_hsi_get_cpus",
        'hsi get_cells -filter {{IP_TYPE == "PROCESSOR"}}',
        "List all processors in the design.",
        "xsct",
    ),
    _t(
        "viv_xsct_hsi_get_peripherals",
        'hsi get_cells -filter {{IP_TYPE == "PERIPHERAL"}}',
        "List all peripherals in the design.",
        "xsct",
    ),
    _t(
        "viv_xsct_hsi_get_memory",
        'hsi get_cells -filter {{IP_TYPE == "MEMORY"}}',
        "List all memory instances in the design.",
        "xsct",
    ),
    _t(
        "viv_xsct_hsi_get_ip_config",
        "hsi get_property CONFIG.{{{param}}} [hsi get_cells {{{{ip}}}}]",
        "Get IP configuration parameter.",
        "xsct",
        [ArgSpec("ip", "IP instance name."), ArgSpec("param", "Parameter name.")],
    ),
    _t(
        "viv_xsct_hsi_get_addr_map",
        "hsi report_addr_map {{{{processor}}}}",
        "Get address map for a processor.",
        "xsct",
        [ArgSpec("processor", "Processor instance name.")],
    ),
    _t(
        "viv_xsct_hsi_generate_drivers",
        "hsi generate_driver -dir {{{{dir}}}}",
        "Generate software drivers.",
        "xsct",
        [ArgSpec("dir", "Output directory.")],
    ),
    _t(
        "viv_xsct_hsi_generate_libs",
        "hsi generate_libs -dir {{{{dir}}}}",
        "Generate software libraries.",
        "xsct",
        [ArgSpec("dir", "Output directory.")],
    ),
    _t(
        "viv_xsct_hsi_close",
        "hsi close_hw_design [hsi current_hw_design]",
        "Close the current HSI hardware design.",
        "xsct",
    ),
    # --- Utility ---
    _t(
        "viv_xsct_exec",
        "exec {{{{command}}}}",
        "Execute a shell command from XSCT.",
        "xsct",
        [ArgSpec("command", "Shell command.")],
    ),
    _t(
        "viv_xsct_version",
        "version",
        "Get XSCT version.",
        "xsct",
    ),
    _t(
        "viv_xsct_help",
        "help {{{{topic}}}}",
        "Get help on an XSCT command.",
        "xsct",
        [ArgSpec("topic", "Command name.")],
    ),
]

# Total count verification happens in tests.
