#!/usr/bin/env python3
"""Generate the Tool Index section for README.md.

Walks all four tool catalogues, groups specs by vendor then category, and
emits a markdown section listing every tool name + one-line summary. Also
produces per-vendor counts for the table.

Usage:
    python3 scripts/gen_tool_index.py            # print to stdout
    python3 scripts/gen_tool_index.py --write     # replace section in README.md
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from fpga_mcp.tool_defs.anlogic import SPECS as A  # noqa: E402
from fpga_mcp.tool_defs.common import SPECS as C  # noqa: E402
from fpga_mcp.tool_defs.quartus import SPECS as Q  # noqa: E402
from fpga_mcp.tool_defs.vivado import SPECS as V  # noqa: E402

SECTION_START = "<!-- BEGIN TOOL INDEX -->"
SECTION_END = "<!-- END TOOL INDEX -->"


def render_section() -> str:
    lines: list[str] = []
    lines.append("## Tool index")
    lines.append("")
    lines.append(
        "Auto-generated by `scripts/gen_tool_index.py` from the live "
        "catalogue. Do not edit by hand — re-run the script after "
        "adding tools."
    )
    lines.append("")

    def emit_vendor(title: str, specs) -> None:
        specs = sorted(specs, key=lambda s: (s.category, s.name))
        lines.append(f"### {title} ({len(specs)})")
        lines.append("")
        by_cat: dict[str, list] = {}
        for s in specs:
            by_cat.setdefault(s.category, []).append(s)
        for cat in sorted(by_cat):
            lines.append(f"<details><summary><code>{cat}</code> ({len(by_cat[cat])})</summary>")
            lines.append("")
            lines.append("| Name | Summary |")
            lines.append("|---|---|")
            for s in by_cat[cat]:
                summary = (s.summary or "").replace("|", "\\|").replace("\n", " ")
                lines.append(f"| `{s.name}` | {summary} |")
            lines.append("")
            lines.append("</details>")
            lines.append("")

    total = len(C) + len(V) + len(Q) + len(A)
    lines.append(
        f"**Total: {total} tools** "
        f"({len(C)} common, {len(V)} vivado, {len(Q)} quartus, {len(A)} anlogic)"
    )
    lines.append("")
    emit_vendor("Common (vendor-agnostic)", C)
    emit_vendor("Vivado", V)
    emit_vendor("Quartus", Q)
    emit_vendor("Anlogic", A)
    return "\n".join(lines)


def replace_in_readme(section: str, readme_path: Path) -> None:
    text = readme_path.read_text(encoding="utf-8")
    pattern = re.compile(
        rf"{re.escape(SECTION_START)}.*?{re.escape(SECTION_END)}",
        re.DOTALL,
    )
    block = f"{SECTION_START}\n{section}\n{SECTION_END}"
    if pattern.search(text):
        new_text = pattern.sub(lambda _: block, text)
    else:
        # Append at the end if no marker exists yet.
        new_text = text.rstrip() + "\n\n" + block + "\n"
    readme_path.write_text(new_text, encoding="utf-8")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument(
        "--write", action="store_true", help="Replace the Tool Index section in README.md"
    )
    args = p.parse_args()

    section = render_section()
    if args.write:
        replace_in_readme(section, ROOT / "README.md")
        print(f"Updated Tool Index in README.md ({section.count('| `')} tools)")
    else:
        print(section)
    return 0


if __name__ == "__main__":
    sys.exit(main())
